"""Build notebooks/motif_evolution_movies.ipynb.

Comprehensive single-notebook movie deliverable:
- Per-motif sections (induction, successor, S-inhibition) each with:
  * Explanation of the pattern to expect
  * 5-size (or 4-size for S-inhibition) across-sizes animation
  * Scaling commentary
- Per-size 3-motif co-evolution animations
- Cross-size scaling summary

All animations use the same color scheme as the existing induction
movie: viridis cmap, vmin=0, vmax = max score within that motif's
data, aspect='auto'. Per-motif vmax differs because score units
differ; within a motif, all panels share scale.

Outputs (notebooks/figures/):
- induction_across_sizes.gif (5 panels)
- successor_across_sizes.gif (5 panels)
- s_inhibition_across_sizes.gif (4 panels; 2.8B excluded under §H4-7-supersede)
- motif_evolution_{70m,160m,410m,1b,2.8b}.gif (per-size co-evolution)
"""

from __future__ import annotations

from pathlib import Path

import nbformat as nbf

ROOT = Path(__file__).resolve().parents[1]
OUT = ROOT / "notebooks" / "motif_evolution_movies.ipynb"


def md(text: str) -> nbf.NotebookNode:
    return nbf.v4.new_markdown_cell(text)


def code(src: str) -> nbf.NotebookNode:
    return nbf.v4.new_code_cell(src)


def build() -> nbf.NotebookNode:
    nb = nbf.v4.new_notebook()
    nb["cells"] = [
        md(
            "# Motif evolution movies — per-motif explanations + per-size co-evolution\n"
            "\n"
            "Animated visualizations of attention-head motif emergence across "
            "Pythia training. Each animation shows the (layer, head) score grid "
            "for one or more motifs, advancing across all 40 §H2-1 checkpoints "
            "from `step0` to `step143000` at ~3 fps (~13 s playback).\n"
            "\n"
            "**Consistent color scheme.** All animations use the **viridis** "
            "colormap with `vmin = 0`, `vmax = motif-specific maximum score "
            "across all sizes`. Per-motif vmax differs because the three "
            "detectors have different score units (induction is bounded in "
            "[0, 1]; successor lift can range to ~3; S-inhibition Δ_h ranges "
            "to ~0.3). Within a motif, all panels share scale so cross-size "
            "comparison is faithful.\n"
            "\n"
            "**Notebook structure:**\n"
            "1. Setup + data load (one place; reused by all sections below).\n"
            "2. **Pattern evolution: Induction** — explanation, 5-size animation, scaling notes.\n"
            "3. **Pattern evolution: Successor** — explanation, 5-size animation, scaling notes.\n"
            "4. **Pattern evolution: S-inhibition** — explanation, 4-size animation (2.8B excluded per §H4-7-supersede), scaling notes.\n"
            "5. **Per-size 3-motif co-evolution** — 5 animations (one per size), 3 motifs side by side per animation.\n"
            "6. **Cross-size scaling summary** — head-count vs detected-count for all 3 motifs.\n"
            "\n"
            "**Outputs.** Inline HTML5 players (interactive in JupyterLab + "
            "GitHub-rendered .ipynb) plus standalone GIFs in "
            "`notebooks/figures/` for sharing or paper-figure use."
        ),
        md("## Setup"),
        code(
            "import os\n"
            "os.environ.setdefault('PYTORCH_ENABLE_MPS_FALLBACK', '1')\n"
            "os.environ.setdefault('HF_HUB_OFFLINE', '1')\n"
            "\n"
            "import sys\n"
            "from pathlib import Path\n"
            "REPO = Path.cwd().parent if Path.cwd().name == 'notebooks' else Path.cwd()\n"
            "if str(REPO) not in sys.path:\n"
            "    sys.path.insert(0, str(REPO))\n"
            "\n"
            "import numpy as np\n"
            "import pandas as pd\n"
            "import matplotlib.pyplot as plt\n"
            "import matplotlib.animation as animation\n"
            "from IPython.display import HTML, display\n"
            "from notebooks._lib.sweep_io import read_long\n"
            "\n"
            "INDUCTION_THRESHOLD = 0.3\n"
            "TAU_LIFT = 0.13496\n"
            "TAU_STRICT = 0.0372\n"
            "TOTAL_HEADS = {'70m': 48, '160m': 144, '410m': 384, '1b': 128, '2.8b': 1024}\n"
            "SIZE_COLOR = {'70m': 'tab:blue', '160m': 'tab:orange', '410m': 'tab:green', '1b': 'tab:red', '2.8b': 'tab:purple'}\n"
            "\n"
            "# SENSITIVITY: scales the vmax of all heatmap animations.\n"
            "#   1.0 = vmax pinned to absolute motif maximum (no saturation; high-end\n"
            "#         differences visible but small changes near threshold compressed).\n"
            "#   0.5 = vmax = 50% of motif maximum (heads above this saturate at yellow,\n"
            "#         BUT mid-range and threshold-crossing dynamics become high-contrast\n"
            "#         and visible — the recommended setting for spotting score *changes*\n"
            "#         in the late-training refinement window).\n"
            "#   0.25 = vmax = 25% of max (very sensitive to threshold-crossing; most\n"
            "#         strong heads saturate).\n"
            "# Lower values = more sensitive to small score changes, more saturation at\n"
            "# the high end. Tradeoff is fundamental.\n"
            "SENSITIVITY = 0.5\n"
            "\n"
            "STEPS = [0, 1, 2, 4, 8, 16, 32, 64, 128, 256, 512,\n"
            "         1000, 2000, 3000, 4000, 5000, 6000, 7000, 8000, 9000,\n"
            "         10000, 11000, 12000, 13000, 14000, 15000, 16000, 17000,\n"
            "         20000, 24000, 29000, 35000, 41000, 49000, 59000, 70000,\n"
            "         84000, 100000, 120000, 143000]\n"
            "\n"
            "FIG_DIR = REPO / 'notebooks' / 'figures'\n"
            "FIG_DIR.mkdir(parents=True, exist_ok=True)"
        ),
        md("## Load all motif sweeps (5 sizes × 3 motifs; 2.8B s_inhibition skipped per §H4-7-supersede)"),
        code(
            "df_ind = pd.concat([\n"
            "    read_long(REPO / 'data' / 'exploration' / 'phase2_induction_sweep.parquet'),\n"
            "    read_long(REPO / 'data' / 'exploration' / 'phase3_1b_induction_sweep.parquet'),\n"
            "    read_long(REPO / 'data' / 'exploration' / 'phase4_2_8b_induction_sweep.parquet'),\n"
            "]).reset_index(drop=True)\n"
            "df_suc = pd.concat([\n"
            "    read_long(REPO / 'data' / 'exploration' / 'phase2_successor_sweep.parquet'),\n"
            "    read_long(REPO / 'data' / 'exploration' / 'phase3_1b_successor_sweep.parquet'),\n"
            "    read_long(REPO / 'data' / 'exploration' / 'phase4_2_8b_successor_sweep.parquet'),\n"
            "]).reset_index(drop=True)\n"
            "df_si = pd.concat([\n"
            "    read_long(REPO / 'data' / 'exploration' / 'phase2_s_inhibition_sweep.parquet'),\n"
            "    read_long(REPO / 'data' / 'exploration' / 'phase3_1b_s_inhibition_sweep.parquet'),\n"
            "]).reset_index(drop=True)\n"
            "MOTIF_DF = {'induction': df_ind, 'successor': df_suc, 's_inhibition': df_si}\n"
            "MOTIF_THRESHOLD = {'induction': INDUCTION_THRESHOLD, 'successor': TAU_LIFT, 's_inhibition': TAU_STRICT}\n"
            "MOTIF_LABEL = {'induction': 'induction (prefix-match)',\n"
            "               'successor': 'successor (lift_dla)',\n"
            "               's_inhibition': 'S-inhibition (Δ_h)'}\n"
            "MOTIF_VMAX_FULL = {motif: float(MOTIF_DF[motif]['score'].max()) for motif in MOTIF_DF}\n"
            "MOTIF_VMAX = {motif: SENSITIVITY * MOTIF_VMAX_FULL[motif] for motif in MOTIF_DF}\n"
            "print(f'\\nSENSITIVITY = {SENSITIVITY}')\n"
            "print(f'Per-motif vmax (used for heatmap saturation):')\n"
            "for motif in MOTIF_DF:\n"
            "    print(f'  {motif:>12s}: vmax = {MOTIF_VMAX[motif]:.4f}  (full max = {MOTIF_VMAX_FULL[motif]:.4f})')\n"
            "for motif, df in MOTIF_DF.items():\n"
            "    sizes = sorted(df['size'].unique().tolist())\n"
            "    print(f'{motif}: vmax={MOTIF_VMAX[motif]:.4f}, sizes={sizes}')"
        ),
        md(
            "## Helper: build per-(size, step) heatmap arrays\n"
            "\n"
            "Returns `frames: list[np.ndarray]` — one (n_layers, n_heads) array "
            "per step in STEPS for the given (size, motif) pair. Returns `None` "
            "if no data exists for that pair (used to detect 2.8B S-inhibition's "
            "missing parquet under §H4-7-supersede)."
        ),
        code(
            "def build_frames(size: str, motif: str):\n"
            "    df = MOTIF_DF[motif]\n"
            "    sub = df[df['size'] == size]\n"
            "    if sub.empty:\n"
            "        return None\n"
            "    n_layers = int(sub['layer'].max() + 1)\n"
            "    n_heads = int(sub['head'].max() + 1)\n"
            "    frames = []\n"
            "    for step in STEPS:\n"
            "        cell = sub[sub['step'] == step]\n"
            "        grid = np.zeros((n_layers, n_heads))\n"
            "        for _, r in cell.iterrows():\n"
            "            grid[int(r['layer']), int(r['head'])] = r['score']\n"
            "        frames.append(grid)\n"
            "    return frames"
        ),
        md(
            "## Helper: render one cross-size animation per motif\n"
            "\n"
            "Builds a single figure with one panel per available size, all panels "
            "sharing the motif's vmin=0 / vmax color scale. Saves a GIF and "
            "returns the FuncAnimation for inline display."
        ),
        code(
            "def render_across_sizes(motif: str, sizes: list[str], out_filename: str, suptitle_prefix: str):\n"
            "    motif_data = {}\n"
            "    for size in sizes:\n"
            "        frames = build_frames(size, motif)\n"
            "        if frames is None:\n"
            "            continue\n"
            "        motif_data[size] = frames\n"
            "    panels = list(motif_data.keys())\n"
            "    if not panels:\n"
            "        print(f'{motif}: no data — skipping')\n"
            "        return None\n"
            "    vmax = MOTIF_VMAX[motif]\n"
            "    fig, axes = plt.subplots(1, len(panels), figsize=(4 * len(panels), 5))\n"
            "    if len(panels) == 1:\n"
            "        axes = [axes]\n"
            "    ims = []\n"
            "    for ax, size in zip(axes, panels):\n"
            "        im = ax.imshow(motif_data[size][0], vmin=0, vmax=vmax, cmap='viridis', aspect='auto')\n"
            "        ax.set_title(f'Pythia-{size} ({TOTAL_HEADS[size]} heads)', fontsize=10)\n"
            "        ax.set_xlabel('head')\n"
            "        ax.set_ylabel('layer')\n"
            "        ims.append(im)\n"
            "    title = fig.suptitle(f'{suptitle_prefix} — step{STEPS[0]} (frame 1/{len(STEPS)})', y=1.0)\n"
            "    fig.colorbar(ims[-1], ax=axes, fraction=0.012, pad=0.02, label=f'{motif} score')\n"
            "    def update(i):\n"
            "        for im, size in zip(ims, panels):\n"
            "            im.set_array(motif_data[size][i])\n"
            "        title.set_text(f'{suptitle_prefix} — step{STEPS[i]} (frame {i+1}/{len(STEPS)})')\n"
            "        return ims + [title]\n"
            "    ani = animation.FuncAnimation(fig, update, frames=len(STEPS), interval=333, blit=False)\n"
            "    out_gif = FIG_DIR / out_filename\n"
            "    ani.save(out_gif, writer=animation.PillowWriter(fps=3))\n"
            "    print(f'  Wrote {out_gif.relative_to(REPO)}')\n"
            "    plt.close(fig)\n"
            "    return ani"
        ),
        # ============================================================
        # Section 2: Induction
        # ============================================================
        md(
            "---\n"
            "\n"
            "## 2. Pattern evolution: Induction\n"
            "\n"
            "**Detector.** Olsson 2022 prefix-matching score: random-token-"
            "repetition sequences of length 100 with a single repeat at "
            "position 50; for each (layer, head), score is mean attention "
            "from positions 51–99 to the position immediately following the "
            "previous occurrence of the current token, averaged over 50 "
            "sequences. Locked threshold > 0.3 (PROJECT_BRIEF.md §4).\n"
            "\n"
            "**Pattern to look for.**\n"
            "- **Mid-to-deep layer concentration.** The induction-head circuit "
            "  is two-layer: a previous-token head (early layer) plus an "
            "  induction head (later layer). The detector measures the "
            "  induction-head step, so heatmap brightness should concentrate "
            "  in mid-to-deep layers, not in the very first 1–2 layers.\n"
            "- **Phase transition near step ~1000–10000.** Olsson 2022 / "
            "  Singh 2024 establish induction-head formation as a narrow "
            "  phase-transition window during training. Watch for a sharp "
            "  brightness step in this range.\n"
            "- **Multiple bright heads at scale.** Smaller models have fewer "
            "  candidate heads; larger models have many bright squares — "
            "  scale unlocks redundancy.\n"
            "\n"
            "**Cross-size scaling.** Pythia-2.8B reaches max_count = **48** "
            "induction heads (4.7% of 1024 heads), the highest of all 5 sizes. "
            "Pythia-1B is a head-count regression on the parameter axis "
            "(128 heads vs 410m's 384), and the head-count axis trajectory "
            "70m → 1b → 160m → 410m → 2.8b is monotonic in induction "
            "max_count (6 → 11 → 17 → 23 → 48)."
        ),
        code(
            "ind_ani = render_across_sizes(\n"
            "    'induction',\n"
            "    ['70m', '160m', '410m', '1b', '2.8b'],\n"
            "    'induction_across_sizes.gif',\n"
            "    'Induction prefix-matching across (layer, head) — 5 Pythia sizes',\n"
            ")\n"
            "if ind_ani is not None:\n"
            "    display(HTML(ind_ani.to_jshtml()))"
        ),
        # ============================================================
        # Section 3: Successor
        # ============================================================
        md(
            "---\n"
            "\n"
            "## 3. Pattern evolution: Successor\n"
            "\n"
            "**Detector.** §SU-1b lift-form cross-category direct logit "
            "attribution. 70 prompts in 4 categories (days / months / "
            "numerals / letters) of the form `[c1, c2, c3, ]`. Score for "
            "each (layer, head) is mean lift = real_DLA(c4) − null_DLA(c4) "
            "where null is computed on a within-category prefix-permuted "
            "version of the prompt set. Locked threshold τ_lift = 0.13496 "
            "(§SU-tau).\n"
            "\n"
            "**Pattern to look for.**\n"
            "- **Deep-layer concentration.** Successor heads are read out by "
            "  the unembedding (since the metric is logit attribution); "
            "  they should cluster in the *last* third of layers in larger "
            "  models. Smaller models show this concentration weakly or not "
            "  at all.\n"
            "- **Late emergence.** Successor heads should appear later in "
            "  training than induction heads (the registered §H1-C "
            "  ordering: μ_ind < μ_suc < μ_si). Watch for brightness "
            "  emerging in the deep-layer band around step ~5000–20000.\n"
            "- **Sparse top-of-curve.** Even at 2.8B, max_count = 14 — "
            "  successor is rarer than induction (which hits 48 at 2.8B). "
            "  The top-of-frame brightness should be concentrated in fewer "
            "  individual cells than induction's.\n"
            "\n"
            "**Cross-size scaling.** Successor max_count grows monotonically "
            "with both parameter and head-count axes: 70m=2 (marginal) → "
            "160m=4 (marginal) → 410m=7 (emerged) → 1b=15 (emerged) → "
            "2.8b=14 (emerged). The 1B → 2.8B step is roughly flat in "
            "max_count despite a ~3× head-count increase, suggesting "
            "saturation may be approaching for successor at this scale "
            "(see also the linear best-fit in `induction_full_sweep.ipynb` "
            "and `h1c_ordering_test.ipynb` §H4-scaling DEFERRED for "
            "comparable per-motif scaling fits)."
        ),
        code(
            "suc_ani = render_across_sizes(\n"
            "    'successor',\n"
            "    ['70m', '160m', '410m', '1b', '2.8b'],\n"
            "    'successor_across_sizes.gif',\n"
            "    'Successor lift_dla across (layer, head) — 5 Pythia sizes',\n"
            ")\n"
            "if suc_ani is not None:\n"
            "    display(HTML(suc_ani.to_jshtml()))"
        ),
        md(
            "### Average successor score over training (per size)\n"
            "\n"
            "Per-size trajectory of the **mean lift_dla among heads passing "
            "τ_lift = 0.13496** at each of the 40 §H2-1 checkpoints. This is "
            "the population-level analog of \"how strong are the *currently "
            "detected* successor heads\" — the count varies across steps as "
            "heads cross the threshold, so the population is changing as well "
            "as the per-head score. Cells with no heads above τ_lift show as "
            "gaps.\n"
            "\n"
            "Reading the curve:\n"
            "- A *rising* trajectory means the average detected head is "
            "  getting stronger AND/OR the threshold-passing population "
            "  shifts toward stronger heads.\n"
            "- A *falling* trajectory means either weaker heads are being "
            "  recruited (broadening the population) or strong heads are "
            "  getting weaker (refinement / competition).\n"
            "- A *flat* trajectory after emergence is the typical mature-"
            "  motif equilibrium.\n"
            "\n"
            "The user noted a possible decrease around step ~84000 in the "
            "2.8B animation — annotated below."
        ),
        code(
            "# Collect (step, avg_score) per size, then scatter + linear best-fit on log10(step).\n"
            "fig, ax = plt.subplots(figsize=(11, 5))\n"
            "all_finite_steps = []\n"
            "for size in ['70m', '160m', '410m', '1b', '2.8b']:\n"
            "    sub = df_suc[df_suc['size'] == size]\n"
            "    if sub.empty:\n"
            "        continue\n"
            "    pts_x = []\n"
            "    pts_y = []\n"
            "    for step in STEPS:\n"
            "        cell = sub[sub['step'] == step]\n"
            "        passing = cell[cell['score'] >= TAU_LIFT]['score']\n"
            "        if len(passing) == 0:\n"
            "            continue\n"
            "        pts_x.append(step)\n"
            "        pts_y.append(float(passing.mean()))\n"
            "    if not pts_x:\n"
            "        continue\n"
            "    pts_x = np.array(pts_x, dtype=float)\n"
            "    pts_y = np.array(pts_y, dtype=float)\n"
            "    all_finite_steps.extend(pts_x.tolist())\n"
            "    color = SIZE_COLOR[size]\n"
            "    ax.scatter(pts_x, pts_y, s=45, alpha=0.85, color=color,\n"
            "               label=f'Pythia-{size}', zorder=3)\n"
            "    # Cubic best fit on log10(step) (degree 3); needs ≥ 4 points.\n"
            "    if len(pts_x) >= 4:\n"
            "        log_x = np.log10(pts_x)\n"
            "        coefs = np.polyfit(log_x, pts_y, 3)\n"
            "        fit_x = np.logspace(np.log10(pts_x.min()), np.log10(pts_x.max()), 120)\n"
            "        fit_y = np.polyval(coefs, np.log10(fit_x))\n"
            "        ax.plot(fit_x, fit_y, '--', color=color, alpha=0.55, zorder=2)\n"
            "    elif len(pts_x) >= 2:\n"
            "        # Fewer than 4 points — fall back to linear on log(step), no fit if < 2.\n"
            "        log_x = np.log10(pts_x)\n"
            "        m, b = np.polyfit(log_x, pts_y, 1)\n"
            "        fit_x = np.logspace(np.log10(pts_x.min()), np.log10(pts_x.max()), 60)\n"
            "        fit_y = m * np.log10(fit_x) + b\n"
            "        ax.plot(fit_x, fit_y, ':', color=color, alpha=0.5, zorder=2)\n"
            "\n"
            "ax.axhline(TAU_LIFT, linestyle=':', color='gray', alpha=0.5,\n"
            "           label=f'τ_lift = {TAU_LIFT}')\n"
            "ax.axvline(84000, linestyle='--', color='black', alpha=0.4,\n"
            "           label='step 84000 (user-noted dip)')\n"
            "x_lo = max(min(all_finite_steps) * 0.7, 100) if all_finite_steps else 1000\n"
            "x_hi = 160000\n"
            "ax.set_xscale('log')\n"
            "ax.set_xlim(x_lo, x_hi)\n"
            "ax.set_xlabel('training step (log)')\n"
            "ax.set_ylabel('mean successor lift_dla among heads ≥ τ_lift')\n"
            "ax.set_title('Average successor score over training, by Pythia size — scatter + per-size cubic fit on log(step)')\n"
            "ax.grid(alpha=0.3, which='both')\n"
            "ax.legend(fontsize=9, loc='upper left')\n"
            "plt.tight_layout()\n"
            "plt.show()\n"
            "\n"
            "print('Per-size avg lift_dla among detected heads at the user-flagged window (step 70k–143k):')\n"
            "print(f'{\"step\":>6s}  ' + '  '.join(f'{s:>7s}' for s in ['70m','160m','410m','1b','2.8b']))\n"
            "windows = [70000, 84000, 100000, 120000, 143000]\n"
            "for step in windows:\n"
            "    parts = [f'{step:>6d}']\n"
            "    for size in ['70m', '160m', '410m', '1b', '2.8b']:\n"
            "        sub = df_suc[(df_suc['size']==size) & (df_suc['step']==step)]\n"
            "        passing = sub[sub['score'] >= TAU_LIFT]['score']\n"
            "        if len(passing) == 0:\n"
            "            parts.append(f'{\"(none)\":>7s}')\n"
            "        else:\n"
            "            parts.append(f'{float(passing.mean()):>+7.3f}')\n"
            "    print('  '.join(parts))"
        ),
        # ============================================================
        # Section 4: S-inhibition
        # ============================================================
        md(
            "---\n"
            "\n"
            "## 4. Pattern evolution: S-inhibition\n"
            "\n"
            "**Detector.** §S-1 path-patching Δ_h with frozen paths. Wang "
            "(2023) IOI prompt set (N=200, BABA + ABBA), ABC position-3 "
            "corruption. For each (sender, NM) pair, Δ_h measures how much "
            "the NM's attention shifts from the indirect-object position "
            "to the duplicate-subject position when the candidate sender is "
            "patched in from the corrupted distribution. Per-sender Δ_h is "
            "averaged over the per-model component-DLA top-4 NMs and the "
            "200 prompts. Locked threshold τ_strict = 0.0372 (§S-tau).\n"
            "\n"
            "**Pattern to look for.**\n"
            "- **Mid-layer concentration.** S-inhibition senders sit "
            "  *upstream* of the Name Movers (which are themselves "
            "  generally in the mid-to-deep range). The S-inhibition "
            "  bright-band should be at lower layer indices than the "
            "  successor bright-band in the same panel.\n"
            "- **Scale-dependent and late-emerging.** The §H2-9-R reframe: "
            "  S-inhibition does not emerge at 70m, emerges marginally at "
            "  160m, and emerges with a clean fit at 410m. Watch for "
            "  near-empty heatmaps at 70m vs. visible structure forming "
            "  late at 410m and 1B.\n"
            "- **Sparse and saturated.** Even at 1B, max_count saturates "
            "  at 3 (matching 410m). The brightness pattern should show "
            "  a small number of consistently-bright cells rather than a "
            "  broad spread.\n"
            "\n"
            "**Cross-size scaling.** S-inhibition max_count: 70m=1 "
            "(censored) → 160m=3 → 410m=3 (saturated) → 1b=3 (saturated, "
            "head-count regression). **2.8B is excluded from this animation** "
            "per §H4-7-supersede: the 2.8B S-inhibition sweep was halted at "
            "8/40 cells (steps 0–64, all early-training, all Δ_h ≈ 0) under "
            "the §H4-7 per-cell-cost escape hatch (~57 min/cell observed vs "
            "~6 min/cell projected). The §H4-scaling gate is therefore "
            "DEFERRED for the count-axis claim. Track 2's 2.8B leg is "
            "parked, not abandoned."
        ),
        code(
            "si_ani = render_across_sizes(\n"
            "    's_inhibition',\n"
            "    ['70m', '160m', '410m', '1b'],\n"
            "    's_inhibition_across_sizes.gif',\n"
            "    'S-inhibition Δ_h across (layer, head) — 4 Pythia sizes (2.8B excluded per §H4-7-supersede)',\n"
            ")\n"
            "if si_ani is not None:\n"
            "    display(HTML(si_ani.to_jshtml()))"
        ),
        # ============================================================
        # Section 5: Per-size 3-motif co-evolution
        # ============================================================
        md(
            "---\n"
            "\n"
            "## 5. Per-size 3-motif co-evolution\n"
            "\n"
            "Each animation below shows all 3 motifs *side by side* for a "
            "single Pythia size, advancing through the 40 §H2-1 checkpoints. "
            "The shared frame index across panels lets you watch motif "
            "*co-emergence* — is induction bright before successor brightens? "
            "Does S-inhibition trail successor as the §H1-C ordering "
            "predicts?\n"
            "\n"
            "**Color scale.** All three panels in each animation use viridis "
            "with vmin=0 and **the motif's own vmax** (not a shared scale "
            "across motifs — successor's lift can reach ~3 while induction "
            "is bounded by 1, so a shared scale would wash out detail). "
            "Within a motif's panel across animations, the scale is "
            "consistent for cross-size comparison.\n"
            "\n"
            "**2.8B has 2 panels** (induction + successor) per §H4-7-supersede."
        ),
        code(
            "MOTIFS_ALL = ['induction', 'successor', 's_inhibition']\n"
            "for size in ['70m', '160m', '410m', '1b', '2.8b']:\n"
            "    motifs_for_size = []\n"
            "    motif_data = {}\n"
            "    for motif in MOTIFS_ALL:\n"
            "        frames = build_frames(size, motif)\n"
            "        if frames is None:\n"
            "            continue\n"
            "        motifs_for_size.append(motif)\n"
            "        motif_data[motif] = frames\n"
            "    n_panels = len(motifs_for_size)\n"
            "    if n_panels == 0:\n"
            "        continue\n"
            "    fig, axes = plt.subplots(1, n_panels, figsize=(5.5 * n_panels, 5))\n"
            "    if n_panels == 1:\n"
            "        axes = [axes]\n"
            "    ims = []\n"
            "    for ax, motif in zip(axes, motifs_for_size):\n"
            "        vmax = MOTIF_VMAX[motif]\n"
            "        im = ax.imshow(motif_data[motif][0], vmin=0, vmax=vmax, cmap='viridis', aspect='auto')\n"
            "        thr = MOTIF_THRESHOLD[motif]\n"
            "        ax.set_title(f'{MOTIF_LABEL[motif]}\\nthreshold = {thr}', fontsize=10)\n"
            "        ax.set_xlabel('head')\n"
            "        ax.set_ylabel('layer')\n"
            "        plt.colorbar(im, ax=ax, fraction=0.04, pad=0.02)\n"
            "        ims.append(im)\n"
            "    title = fig.suptitle(\n"
            "        f'Pythia-{size} ({TOTAL_HEADS[size]} heads) — motif co-evolution at step{STEPS[0]} (frame 1/{len(STEPS)})',\n"
            "        y=1.0,\n"
            "    )\n"
            "    if size == '2.8b' and 's_inhibition' not in motifs_for_size:\n"
            "        fig.text(0.99, 0.01,\n"
            "                 'S-inhibition omitted: sweep halted at 8/40 cells (§H4-7-supersede)',\n"
            "                 ha='right', va='bottom', fontsize=8, style='italic', color='gray')\n"
            "    def make_update(ims_local, motifs_local, motif_data_local, title_local, size_local):\n"
            "        def _update(i):\n"
            "            for im, motif in zip(ims_local, motifs_local):\n"
            "                im.set_array(motif_data_local[motif][i])\n"
            "            title_local.set_text(\n"
            "                f'Pythia-{size_local} ({TOTAL_HEADS[size_local]} heads) — motif co-evolution '\n"
            "                f'at step{STEPS[i]} (frame {i+1}/{len(STEPS)})'\n"
            "            )\n"
            "            return ims_local + [title_local]\n"
            "        return _update\n"
            "    update = make_update(ims, motifs_for_size, motif_data, title, size)\n"
            "    ani = animation.FuncAnimation(fig, update, frames=len(STEPS), interval=333, blit=False)\n"
            "    out_gif = FIG_DIR / f'motif_evolution_{size}.gif'\n"
            "    ani.save(out_gif, writer=animation.PillowWriter(fps=3))\n"
            "    print(f'  Pythia-{size}: {n_panels} panels, wrote {out_gif.relative_to(REPO)}')\n"
            "    plt.close(fig)\n"
            "    display(HTML(f'<h3>Pythia-{size}</h3>'))\n"
            "    display(HTML(ani.to_jshtml()))"
        ),
        # ============================================================
        # Section 6: Cross-size scaling summary
        # ============================================================
        md(
            "---\n"
            "\n"
            "## 6. Cross-size scaling summary (head-count axis)\n"
            "\n"
            "Final-checkpoint max_count for each motif at each size:"
        ),
        code(
            "summary_rows = []\n"
            "for size in ['70m', '160m', '410m', '1b', '2.8b']:\n"
            "    th = TOTAL_HEADS[size]\n"
            "    row = {'size': size, 'total_heads': th}\n"
            "    for motif in MOTIFS_ALL:\n"
            "        df = MOTIF_DF[motif]\n"
            "        sub = df[df['size'] == size]\n"
            "        if sub.empty:\n"
            "            row[motif] = None\n"
            "            continue\n"
            "        thr = MOTIF_THRESHOLD[motif]\n"
            "        passes = (sub['score'] > thr) if motif == 'induction' else (sub['score'] >= thr)\n"
            "        sub2 = sub.copy()\n"
            "        sub2['passes'] = passes.astype(int)\n"
            "        max_count = int(sub2.groupby('step')['passes'].sum().max())\n"
            "        row[motif] = max_count\n"
            "    summary_rows.append(row)\n"
            "summary_df = pd.DataFrame(summary_rows)\n"
            "print('max_count by (size, motif):')\n"
            "print(summary_df.to_string(index=False))\n"
            "print()\n"
            "print('Density (max_count / total_heads):')\n"
            "for _, r in summary_df.iterrows():\n"
            "    parts = [f'{r[\"size\"]:>5s} ({r[\"total_heads\"]:>4d} heads):']\n"
            "    for motif in MOTIFS_ALL:\n"
            "        v = r[motif]\n"
            "        if v is None:\n"
            "            parts.append(f'{motif} = (n/a)')\n"
            "        else:\n"
            "            parts.append(f'{motif} = {v}/{r[\"total_heads\"]} = {v/r[\"total_heads\"]*100:.1f}%')\n"
            "    print('  ' + '  '.join(parts))"
        ),
        code(
            "fig, axes = plt.subplots(1, 3, figsize=(15, 4.5), sharey=False)\n"
            "ordered = sorted(['70m', '160m', '410m', '1b', '2.8b'], key=lambda s: TOTAL_HEADS[s])\n"
            "xs_full = np.array([TOTAL_HEADS[s] for s in ordered], dtype=float)\n"
            "for ax, motif, color in zip(axes, MOTIFS_ALL, ['tab:blue', 'tab:green', 'tab:red']):\n"
            "    sub = summary_df[['size', motif]].dropna()\n"
            "    sub_sorted = sub.set_index('size').loc[[s for s in ordered if s in sub['size'].tolist()]]\n"
            "    xs = np.array([TOTAL_HEADS[s] for s in sub_sorted.index], dtype=float)\n"
            "    ys = np.array(sub_sorted[motif].values, dtype=float)\n"
            "    if len(xs) >= 3:\n"
            "        # Quadratic best fit: y = a*x^2 + b*x + c\n"
            "        a, b, c = np.polyfit(xs, ys, 2)\n"
            "        y_pred = a * xs ** 2 + b * xs + c\n"
            "        ss_res = float(np.sum((ys - y_pred) ** 2))\n"
            "        ss_tot = float(np.sum((ys - ys.mean()) ** 2))\n"
            "        r2 = 1.0 - ss_res / ss_tot if ss_tot > 0 else float('nan')\n"
            "        fit_x = np.linspace(0, xs.max() * 1.05, 100)\n"
            "        fit_y = a * fit_x ** 2 + b * fit_x + c\n"
            "        # Format equation with appropriate sign handling\n"
            "        sign_b = '+' if b >= 0 else '-'\n"
            "        sign_c = '+' if c >= 0 else '-'\n"
            "        eq = f'y = {a:+.2e}·x² {sign_b} {abs(b):.4f}·x {sign_c} {abs(c):.2f}  (R²={r2:.3f})'\n"
            "        ax.plot(fit_x, fit_y, '--', color=color, alpha=0.6, label=eq)\n"
            "    elif len(xs) >= 2:\n"
            "        # Fallback to linear if only 2 points (can't fit a parabola).\n"
            "        slope, intercept = np.polyfit(xs, ys, 1)\n"
            "        y_pred = slope * xs + intercept\n"
            "        ss_res = float(np.sum((ys - y_pred) ** 2))\n"
            "        ss_tot = float(np.sum((ys - ys.mean()) ** 2))\n"
            "        r2 = 1.0 - ss_res / ss_tot if ss_tot > 0 else float('nan')\n"
            "        fit_x = np.linspace(0, xs.max() * 1.05, 100)\n"
            "        fit_y = slope * fit_x + intercept\n"
            "        eq = f'y = {slope:.4f}x {\"+\" if intercept >= 0 else \"-\"} {abs(intercept):.2f}  (R²={r2:.3f})  [linear: only 2 points]'\n"
            "        ax.plot(fit_x, fit_y, '--', color=color, alpha=0.6, label=eq)\n"
            "    for size in sub_sorted.index:\n"
            "        x = TOTAL_HEADS[size]; y = sub_sorted.loc[size, motif]\n"
            "        ax.scatter([x], [y], s=120, color=SIZE_COLOR[size], zorder=3)\n"
            "        ax.annotate(size, (x, y), textcoords='offset points', xytext=(7, 4), fontsize=9)\n"
            "    ax.set_xlabel('total attention heads per model')\n"
            "    ax.set_ylabel(f'max_count of {motif} heads')\n"
            "    ax.set_title(f'{motif} max_count vs total heads')\n"
            "    ax.grid(alpha=0.3)\n"
            "    ax.legend(fontsize=9, loc='upper left')\n"
            "fig.suptitle('Cross-size scaling: total attention heads vs detected motif heads (quadratic fit per motif)', y=1.02)\n"
            "plt.tight_layout()\n"
            "plt.show()"
        ),
        md(
            "### Reading the scaling fits\n"
            "\n"
            "The three per-motif **quadratic** fits above (head-count axis, "
            "linear scales, degree 2) give a quick read on the operationally "
            "relevant scaling shape for each motif. Quadratic captures "
            "concave-up acceleration (positive `a`) or concave-down "
            "saturation (negative `a`) that a linear fit misses:\n"
            "\n"
            "- **Induction**: 5-point fit. Watch the sign of `a`: positive `a` "
            "  means induction-head count *accelerates* with total head count "
            "  (super-linear scaling); negative means saturation begins to "
            "  bend the curve over.\n"
            "- **Successor**: 5-point fit. The 1B → 2.8B step is near-flat "
            "  (max=15 → 14). Quadratic should pick this up as a negative "
            "  `a` (concave-down) if the trend is genuinely saturating, or "
            "  near-zero `a` if the apparent flatness is single-point noise.\n"
            "- **S-inhibition**: 4-point fit (no 2.8B per §H4-7-supersede). "
            "  Saturation at max=3 from 160m onward dominates; expect the "
            "  quadratic to bend hard or fit poorly.\n"
            "\n"
            "**Caveats.** Quadratic fits over 4 or 5 data points are *very* "
            "sensitive to individual points — the R² will look reasonable "
            "(quadratic is a strict super-set of linear) but the `a` "
            "coefficient is dominated by whichever point is most extreme. "
            "These fits are descriptive summaries of the observed cross-size "
            "differences, not predictive scaling laws. With only 5 points, "
            "the quadratic is mostly capturing whether the trend is "
            "concave-up vs concave-down rather than learning a real "
            "scaling law."
        ),
        md(
            "## Files written (`notebooks/figures/`)\n"
            "\n"
            "**Across-sizes per-motif (3 GIFs):**\n"
            "- `induction_across_sizes.gif` — 5 panels: 70m / 160m / 410m / 1b / 2.8b\n"
            "- `successor_across_sizes.gif` — 5 panels\n"
            "- `s_inhibition_across_sizes.gif` — 4 panels (2.8B excluded per §H4-7-supersede)\n"
            "\n"
            "**Per-size co-evolution (5 GIFs):**\n"
            "- `motif_evolution_70m.gif` — 3 panels: ind / suc / si\n"
            "- `motif_evolution_160m.gif` — 3 panels\n"
            "- `motif_evolution_410m.gif` — 3 panels\n"
            "- `motif_evolution_1b.gif` — 3 panels\n"
            "- `motif_evolution_2.8b.gif` — **2 panels** (ind / suc; S-inhibition omitted per §H4-7-supersede)\n"
            "\n"
            "Inline HTML5 players above each section have play / pause / "
            "scrub controls (visible in JupyterLab and GitHub-rendered "
            ".ipynb). The `induction_evolution.gif` from "
            "`induction_full_sweep.ipynb` is the same animation as "
            "`induction_across_sizes.gif` here, with the same color scheme; "
            "kept in two places for ease of access."
        ),
    ]
    return nb


def main() -> None:
    nb = build()
    OUT.parent.mkdir(parents=True, exist_ok=True)
    nbf.write(nb, OUT)
    print(f"Wrote {OUT.relative_to(ROOT)}")


if __name__ == "__main__":
    main()
