"""Build notebooks/h1c_ordering_test.ipynb.

Phase 2 headline deliverable: cross-motif H1-C ordering test (HYPOTHESIS.md
§H2-9 deliverable 4). Loads the three Phase 2 sweep parquets + per-prompt
caches, fits μ_{s,m} with bootstrap CIs, runs the joint H1-C permutation
test, and reports the seven sub-deliverables locked in §H2-9.
"""

from __future__ import annotations

from pathlib import Path

import nbformat as nbf

ROOT = Path(__file__).resolve().parents[1]
OUT = ROOT / "notebooks" / "h1c_ordering_test.ipynb"


def md(text: str) -> nbf.NotebookNode:
    return nbf.v4.new_markdown_cell(text)


def code(src: str) -> nbf.NotebookNode:
    return nbf.v4.new_code_cell(src)


def build() -> nbf.NotebookNode:
    nb = nbf.v4.new_notebook()
    nb["cells"] = [
        md(
            "# H1-C ordering test — joint verdict across 3 motifs × 3 sizes\n"
            "\n"
            "**Phase 2 headline deliverable** (HYPOTHESIS.md §H2-9 deliverable 4).\n"
            "\n"
            "## What this notebook claims (and does not claim)\n"
            "\n"
            "The registered H1-C hypothesis is **μ_induction < μ_successor < μ_S-inhibition** in all three Pythia sizes (70m, 160m, 410m). Under H_0 of exchangeable per-size order, the joint sign test gives p = (1/6)³ ≈ 0.00463; the locked falsification gate is **p < 0.005**.\n"
            "\n"
            "We pass the gate. **We do not, on the strength of that pass alone, claim the registered compositional account is robustly supported.** The joint sign test is a 3-bit observation — for each size, did the predicted strict ordering hold? — and is silent on:\n"
            "\n"
            "1. Whether ordering pairs are supported by *signal* (well-fit μ values with non-overlapping CIs) or by *censoring* (one motif failing to emerge during training, vacuously satisfying the inequality against any earlier motif).\n"
            "2. Whether the temporal ordering reflects a *compositional architectural ordering* in the forward pass, or merely a coincidence of training-time emergence ordering.\n"
            "3. Whether the heads identified as instances of each motif are *stable* across training (i.e., whether \"emergence step\" is a coherent quantity for that motif).\n"
            "\n"
            "Per the reframe registered in HYPOTHESIS.md §H2-9-R: **the headline result is scale-dependent emergence with a single robust per-size confirmation (Pythia-410m).** At 160m, the (successor, S-inhibition) ordering passes only because S-inhibition's logistic fit hits the upper sentinel; the bootstrap CI overlaps successor's CI. At 70m, S-inhibition does not emerge during training (max_count=1, right-censored at step143000), and the ordering passes vacuously. Sub-deliverables 3 (bootstrap reversal rate), 5 (depth-vs-temporal), and 7 (verdict) interpret these caveats explicitly.\n"
            "\n"
            "## Inputs and locked thresholds\n"
            "\n"
            "40-cell × 3-size sweep parquets and per-prompt cache `.npz` files for each motif (induction, successor, S-inhibition), produced by `_run_phase2_*_sweep.py`. Pre-locked thresholds: induction prefix-match > 0.3 (brief §4); successor τ_lift = 0.13496 (§SU-tau); S-inhibition τ_strict = 0.0372 (§S-tau).\n"
            "\n"
            "## Sub-deliverables (§H2-9)\n"
            "\n"
            "1. Joint H1-C sign-test verdict (the registered gate).\n"
            "2. Emergence-step μ table with bootstrap CIs across all 9 (size, motif) cells.\n"
            "3. **Bootstrap reversal-rate per (size, pair)** — empirical reframe of the original \"per-pair descriptive p-values\" sub-deliverable. Replaces the prior-under-exchangeability with the fraction of B=1000 bootstrap replicates in which the predicted ordering does NOT hold.\n"
            "4. Side-by-side emergence-comparison curves (3 panels, one per size; three motif curves per panel).\n"
            "5. Major differences between the three head types — depth, count saturation, cross-category breadth, identity stability.\n"
            "6. Threshold-sensitivity check (μ point estimates with B=1000 bootstrap envelopes at ± 25% threshold variants).\n"
            "7. Verdict, reframed for scale-dependence."
        ),
        md(
            "## Methodological audit trail\n"
            "\n"
            "A reviewer reading just the four Phase-2 deliverables (this notebook + the three `_full_sweep` notebooks) would not see the upstream tooling validation, the copy-suppression pivot, or the threshold-locking notebooks. The full audit trail is:\n"
            "\n"
            "**Tooling validation.** [`tigges_ioi_replication.ipynb`](./tigges_ioi_replication.ipynb) — Tigges 2024 IOI emergence-curve replication on Pythia. Max abs-diff 0.066 < 0.10 vs Tigges 2024 at the 4 directly-shared steps. This is the make-or-break MPS-numerics check that gates every downstream patching result.\n"
            "\n"
            "**Pivot from copy-suppression to S-inhibition.** [`copy_suppression_proof.ipynb`](./copy_suppression_proof.ipynb), [`copy_suppression_pythia_proof.ipynb`](./copy_suppression_pythia_proof.ipynb), [`copy_suppression_emergence_exploration.ipynb`](./copy_suppression_emergence_exploration.ipynb) — pre-pivot evidence that copy-suppression's CSPA proxy fails the GPT-2 gate on Pythia. The pivot to S-inhibition is documented in `PILOT_RESULTS.md` and the `HYPOTHESIS.md` Pivot hypothesis (H1-C) + the 2026-05-05 validation-reframing amendment block.\n"
            "\n"
            "**S-inhibition detector validation.** [`s_inhibition_proof.ipynb`](./s_inhibition_proof.ipynb) — GPT-2 small replication of Wang 2022 S-inhibition heads. The strict σ-criterion failed by 0.019σ; rank-based override accepted under §S-5b/c (Wang's 4 = ranks #1-#4 of 144). The reasoning is recorded in HYPOTHESIS.md.\n"
            "\n"
            "**Successor detector validation.** [`successor_proof.ipynb`](./successor_proof.ipynb) — GPT-2 small L9H1 reproduction (rank #1 by §SU-1b lift score). The lift-form supersede of the original real-DLA score is documented in HYPOTHESIS.md §SU-1b after a smoke-test failure of the original spec.\n"
            "\n"
            "**Per-motif Phase 2 sweeps.** [`induction_full_sweep.ipynb`](./induction_full_sweep.ipynb), [`successor_full_sweep.ipynb`](./successor_full_sweep.ipynb), [`s_inhibition_full_sweep.ipynb`](./s_inhibition_full_sweep.ipynb) — 40-cell × 3-size emergence curves with bootstrap CIs per motif. The H1-C ordering verdict in this notebook composes those three.\n"
            "\n"
            "**Pre-registration record.** `HYPOTHESIS.md` is the registered specification with appended amendments (§SU, §SU-1b, §SU-tau, §H2, §H2-9-R reframe). Each amendment block has a commit timestamp; the amendment chain is the audit log.\n"
        ),
        md("## Setup"),
        code(
            "import os\n"
            "os.environ.setdefault('PYTORCH_ENABLE_MPS_FALLBACK', '1')\n"
            "\n"
            "import sys\n"
            "from pathlib import Path\n"
            "REPO = Path.cwd().parent if Path.cwd().name == 'notebooks' else Path.cwd()\n"
            "if str(REPO) not in sys.path:\n"
            "    sys.path.insert(0, str(REPO))\n"
            "\n"
            "import numpy as np\n"
            "import pandas as pd\n"
            "import matplotlib.pyplot as plt\n"
            "from notebooks._lib.sweep_io import read_long\n"
            "from src.analysis.phase2_logistic import (\n"
            "    tiered_fit, evaluate_ordering, joint_h1c_test, RIGHT_CENSOR_STEP,\n"
            ")\n"
            "from src.analysis.phase2_bootstrap import (\n"
            "    bootstrap_induction, bootstrap_successor, bootstrap_s_inhibition,\n"
            "    summarize_bootstrap, THRESHOLD_SENSITIVITY_FRACTIONS,\n"
            ")\n"
            "\n"
            "SIZES = ['70m', '160m', '410m', '1b']\n"
            "REGISTERED_SIZES = ['70m', '160m', '410m']  # the 3 sizes locked into §H1-C / §H2-5; 1b is a separate §H3-scale gate\n"
            "MOTIFS = ['induction', 'successor', 's_inhibition']\n"
            "SIZE_COLOR = {'70m': 'tab:blue', '160m': 'tab:orange', '410m': 'tab:green', '1b': 'tab:red'}\n"
            "MOTIF_MARKER = {'induction': '^', 'successor': 's', 's_inhibition': 'o'}\n"
            "MOTIF_LINESTYLE = {'induction': '--', 'successor': '-.', 's_inhibition': '-'}\n"
            "\n"
            "INDUCTION_THRESHOLD = 0.3\n"
            "TAU_LIFT = 0.13496\n"
            "TAU_STRICT = 0.0372\n"
            "\n"
            "def sweep_path(motif: str, size: str) -> Path:\n"
            "    \"\"\"phase2_*_sweep.parquet for {70m,160m,410m}; phase3_1b_*_sweep.parquet for 1b.\"\"\"\n"
            "    if size == '1b':\n"
            "        return REPO / 'data' / 'exploration' / f'phase3_1b_{motif}_sweep.parquet'\n"
            "    return REPO / 'data' / 'exploration' / f'phase2_{motif}_sweep.parquet'\n"
            "\n"
            "def per_cell_dir(motif: str, size: str) -> Path:\n"
            "    suffix = 'per_seq' if motif == 'induction' else 'per_prompt'\n"
            "    if size == '1b':\n"
            "        return REPO / 'data' / 'exploration' / f'phase3_1b_{motif}_{suffix}'\n"
            "    return REPO / 'data' / 'exploration' / f'phase2_{motif}_{suffix}'"
        ),
        md(
            "## Sub-deliverable 2 — Emergence-step μ table with bootstrap CIs\n"
            "\n"
            "For each (size, motif), fit logistic per §H2-3 tiered handling and "
            "compute B=1000 prompt-bootstrap 95% CI on μ per §H2-2."
        ),
        code(
            "# Dedup parquet paths before loading: phase2_*_sweep.parquet holds all three\n"
            "# phase2 sizes in one file, so sweep_path('induction','70m') ==\n"
            "# sweep_path('induction','410m'). Iterating over SIZES naïvely triple-counts.\n"
            "def _load_motif(motif: str) -> pd.DataFrame:\n"
            "    paths = list(dict.fromkeys(sweep_path(motif, s) for s in SIZES))\n"
            "    return pd.concat([read_long(p) for p in paths]).reset_index(drop=True)\n"
            "df_ind = _load_motif('induction')\n"
            "df_suc = _load_motif('successor')\n"
            "df_si = _load_motif('s_inhibition')\n"
            "\n"
            "def per_size_curve(df, size, threshold, comparator='gt'):\n"
            "    sub = df[df['size'] == size].copy()\n"
            "    if comparator == 'gt':\n"
            "        passes = (sub['score'] > threshold).astype(int)\n"
            "    else:\n"
            "        passes = (sub['score'] >= threshold).astype(int)\n"
            "    sub['passes'] = passes\n"
            "    grouped = sub.groupby('step')['passes'].sum().sort_index()\n"
            "    return grouped.index.values, grouped.values\n"
            "\n"
            "rng = np.random.default_rng(0)\n"
            "rows = []\n"
            "bootstrap_mus = {}  # {(size, motif): mus_array of shape (B,)} for §3 reversal rate\n"
            "for size in SIZES:\n"
            "    for motif, df, threshold, comparator in [\n"
            "        ('induction', df_ind, INDUCTION_THRESHOLD, 'gt'),\n"
            "        ('successor', df_suc, TAU_LIFT, 'gte'),\n"
            "        ('s_inhibition', df_si, TAU_STRICT, 'gte'),\n"
            "    ]:\n"
            "        steps, counts = per_size_curve(df, size, threshold, comparator)\n"
            "        # Bootstrap on cached per-prompt arrays\n"
            "        cache_dir = REPO / 'data' / 'exploration'\n"
            "        if motif == 'induction':\n"
            "            per_seq = {int(s): np.load(per_cell_dir('induction', size) / f'{size}_step{s}.npz')['per_sequence_scores'] for s in steps}\n"
            "            mus, mu_point = bootstrap_induction(per_seq, threshold, rng, B=1000)\n"
            "        elif motif == 'successor':\n"
            "            per_pp = {}\n"
            "            for s in steps:\n"
            "                npz = np.load(per_cell_dir('successor', size) / f'{size}_step{s}.npz')\n"
            "                per_pp[int(s)] = {'real': npz['per_prompt_real'], 'null': npz['per_prompt_null'], 'cats': npz['prompt_categories']}\n"
            "            mus, mu_point = bootstrap_successor(per_pp, threshold, rng, B=1000)\n"
            "        else:\n"
            "            per_pp = {}\n"
            "            nm_layers = {}\n"
            "            for s in steps:\n"
            "                npz = np.load(per_cell_dir('s_inhibition', size) / f'{size}_step{s}.npz')\n"
            "                per_pp[int(s)] = npz['per_prompt_delta']\n"
            "                nm_layers[int(s)] = npz['nm_heads'][:, 0].tolist()\n"
            "            a_grp = df_si[(df_si['size'] == size) & (df_si['step'] == steps[0])]\n"
            "            n_layers = int(a_grp['layer'].max() + 1); n_heads = int(a_grp['head'].max() + 1)\n"
            "            sender_layers = np.array([L for L in range(n_layers) for _ in range(n_heads)])\n"
            "            mus, mu_point = bootstrap_s_inhibition(per_pp, threshold, nm_layers, sender_layers, rng, B=1000)\n"
            "        bres = summarize_bootstrap(size, motif, threshold, mus, mu_point)\n"
            "        bootstrap_mus[(size, motif)] = mus  # store for reversal-rate computation\n"
            "        # Per §H2-3, marginal regime uses bootstrap-median μ as point estimate.\n"
            "        fr = tiered_fit(size, motif, steps, counts,\n"
            "                        bootstrap_median_mu=bres.mu_bootstrap_median)\n"
            "        rows.append(dict(\n"
            "            size=size, motif=motif, regime=fr.regime, max_count=fr.max_count,\n"
            "            mu_point=fr.mu, mu_boot_median=bres.mu_bootstrap_median,\n"
            "            ci_low=bres.mu_ci_low, ci_high=bres.mu_ci_high,\n"
            "        ))\n"
            "mu_df = pd.DataFrame(rows)\n"
            "print(mu_df.to_string(index=False, float_format=lambda v: f'{v:.0f}' if v == int(v) else f'{v:.2f}'))"
        ),
        md(
            "## Sub-deliverable 1 — Joint H1-C permutation-test verdict\n"
            "\n"
            "For each size: evaluate μ_ind < μ_suc < μ_S-inhibition strict ordering "
            "with §H2-4 ties-fail policy. Joint verdict per §H2-5: passes if all "
            "3 sizes hold strict ordering."
        ),
        code(
            "# Per-size ordering check across all 4 sizes (visualization).\n"
            "# Joint H1-C / §H2-5 gate is locked to REGISTERED_SIZES (the 3 sizes); 1B has its own §H3-scale gate.\n"
            "orderings_all = []\n"
            "for size in SIZES:\n"
            "    sub = mu_df[mu_df['size'] == size]\n"
            "    mu_ind = float(sub[sub['motif'] == 'induction']['mu_point'].iloc[0])\n"
            "    mu_suc = float(sub[sub['motif'] == 'successor']['mu_point'].iloc[0])\n"
            "    mu_si = float(sub[sub['motif'] == 's_inhibition']['mu_point'].iloc[0])\n"
            "    orderings_all.append(evaluate_ordering(size, mu_ind, mu_suc, mu_si))\n"
            "\n"
            "# §H1-C joint test operates on the 3 registered sizes only.\n"
            "orderings = [o for o in orderings_all if o.size in REGISTERED_SIZES]\n"
            "verdict = joint_h1c_test(orderings)\n"
            "print('Per-size ordering check (4 sizes; §H1-C joint test uses the 3 registered sizes):')\n"
            "for o in orderings_all:\n"
            "    in_gate = ' [in §H1-C gate]' if o.size in REGISTERED_SIZES else ' [§H3-scale]'\n"
            "    print(f'  Pythia-{o.size}{in_gate}: μ_ind={o.mu_induction:.0f}, μ_suc={o.mu_successor:.0f}, μ_si={o.mu_s_inhibition:.0f}')\n"
            "    print(f'    pair (ind→suc): {\"HOLDS\" if o.pair_ind_suc_holds else \"FAILS\"}'\n"
            "          + (' [undetermined]' if o.pair_ind_suc_undetermined else ''))\n"
            "    print(f'    pair (suc→si):  {\"HOLDS\" if o.pair_suc_si_holds else \"FAILS\"}'\n"
            "          + (' [undetermined]' if o.pair_suc_si_undetermined else ''))\n"
            "    print(f'    strict ordering: {\"HOLDS\" if o.holds_strict else \"FAILS\"}')\n"
            "print()\n"
            "print(f'Joint H1-C verdict (registered, 3 sizes; n_sizes_holding={verdict.n_sizes_holding}/3):')\n"
            "print(f'  joint p (under H_0): {verdict.joint_p_under_h0}')\n"
            "print(f'  PASSES gate (p < 0.005)? {verdict.passes}')"
        ),
        md(
            "## Sub-deliverable 4 — Side-by-side emergence curves\n"
            "\n"
            "Three panels, one per Pythia size. Each panel shows induction, "
            "successor, and S-inhibition count-vs-step curves with their "
            "respective μ point estimates and 95% bootstrap CIs marked."
        ),
        code(
            "fig, axes = plt.subplots(1, len(SIZES), figsize=(6 * len(SIZES), 5), sharey=False)\n"
            "for ax, size in zip(axes, SIZES):\n"
            "    for motif, df, threshold, comparator in [\n"
            "        ('induction', df_ind, INDUCTION_THRESHOLD, 'gt'),\n"
            "        ('successor', df_suc, TAU_LIFT, 'gte'),\n"
            "        ('s_inhibition', df_si, TAU_STRICT, 'gte'),\n"
            "    ]:\n"
            "        steps, counts = per_size_curve(df, size, threshold, comparator)\n"
            "        ax.plot(steps, counts,\n"
            "                marker=MOTIF_MARKER[motif],\n"
            "                linestyle=MOTIF_LINESTYLE[motif],\n"
            "                color=SIZE_COLOR[size],\n"
            "                alpha=0.85, label=motif)\n"
            "        m_row = mu_df[(mu_df['size'] == size) & (mu_df['motif'] == motif)].iloc[0]\n"
            "        if np.isfinite(m_row['mu_point']) and m_row['mu_point'] < RIGHT_CENSOR_STEP - 1:\n"
            "            ax.axvline(m_row['mu_point'], linestyle=':', alpha=0.5,\n"
            "                       color=SIZE_COLOR[size])\n"
            "    ax.set_xscale('symlog', linthresh=100)\n"
            "    ax.set_xlim(100, 150000)\n"
            "    ax.set_xlabel('training step (symlog)')\n"
            "    if size == SIZES[0]:\n"
            "        ax.set_ylabel('count of heads passing motif threshold')\n"
            "    ax.set_title(f'Pythia-{size}: H1-C ordering check')\n"
            "    ax.grid(alpha=0.3)\n"
            "    ax.legend(fontsize=9, loc='upper left')\n"
            "fig.suptitle('Side-by-side emergence: induction (▲) → successor (■) → S-inhibition (●)', y=1.02)\n"
            "plt.tight_layout()\n"
            "plt.show()"
        ),
        md(
            "## Sub-deliverable 4b — Layer depth over training: where each motif lives, evolved\n"
            "\n"
            "For each size and motif, plot the **top-head normalized depth** "
            "and **score-weighted centroid normalized depth** across training "
            "steps. This is the time-evolution complement to sub-deliverable "
            "5's final-checkpoint depth snapshot.\n"
            "\n"
            "If the H1-C compositional account is right, the *corrective* "
            "mechanism (S-inhibition) should sit at deeper normalized depth "
            "than the upstream copying mechanisms (induction, successor) "
            "throughout training, not just at the final checkpoint. Tracking "
            "depth over time also surfaces identity-switch events (a top head "
            "at step8k getting replaced by a different layer's head at "
            "step50k) that the static snapshot would miss."
        ),
        code(
            "def depth_trajectory(df, size, score_threshold=None):\n"
            "    \"\"\"Per-cell top-head and score-weighted-centroid normalized depth.\"\"\"\n"
            "    sub = df[df['size'] == size]\n"
            "    rows = []\n"
            "    for step in sorted(sub['step'].unique()):\n"
            "        cell = sub[sub['step'] == step]\n"
            "        if cell.empty:\n"
            "            continue\n"
            "        n_layers = int(cell['layer'].max() + 1)\n"
            "        scores = cell['score'].values.astype(float)\n"
            "        layers = cell['layer'].values.astype(float)\n"
            "        # Top-head normalized depth\n"
            "        top_idx_local = int(np.argmax(scores))\n"
            "        top_norm = float(layers[top_idx_local]) / max(n_layers - 1, 1)\n"
            "        # Score-weighted centroid (clip negatives so anti-motif heads don't pull)\n"
            "        weights = np.clip(scores, 0.0, None)\n"
            "        if weights.sum() > 0:\n"
            "            wl = float((weights * layers).sum() / weights.sum())\n"
            "            wnorm = wl / max(n_layers - 1, 1)\n"
            "        else:\n"
            "            wnorm = float('nan')\n"
            "        rows.append(dict(\n"
            "            step=int(step),\n"
            "            top_norm_depth=top_norm,\n"
            "            weighted_norm_depth=wnorm,\n"
            "            max_score=float(scores.max()),\n"
            "        ))\n"
            "    return pd.DataFrame(rows)\n"
            "\n"
            "depth_traj = {}\n"
            "for size in SIZES:\n"
            "    depth_traj[size] = {\n"
            "        'induction': depth_trajectory(df_ind, size),\n"
            "        'successor': depth_trajectory(df_suc, size),\n"
            "        's_inhibition': depth_trajectory(df_si, size),\n"
            "    }"
        ),
        code(
            "fig, axes = plt.subplots(2, len(SIZES), figsize=(6 * len(SIZES), 9), sharex='col', sharey=False)\n"
            "for col, size in enumerate(SIZES):\n"
            "    # Top row: top-head normalized depth\n"
            "    ax = axes[0, col]\n"
            "    for motif in MOTIFS:\n"
            "        traj = depth_traj[size][motif]\n"
            "        ax.plot(traj['step'], traj['top_norm_depth'],\n"
            "                marker=MOTIF_MARKER[motif], linestyle=MOTIF_LINESTYLE[motif],\n"
            "                color=SIZE_COLOR[size], alpha=0.8, label=motif, markersize=4)\n"
            "    ax.set_xscale('symlog', linthresh=100)\n"
            "    ax.set_xlim(100, 150000)\n"
            "    ax.set_ylim(-0.05, 1.05)\n"
            "    ax.set_title(f'Pythia-{size}: top-head depth')\n"
            "    if col == 0:\n"
            "        ax.set_ylabel('top-head normalized depth')\n"
            "    ax.grid(alpha=0.3)\n"
            "    if col == len(SIZES) - 1:\n"
            "        ax.legend(fontsize=9, loc='upper left')\n"
            "    # Add μ point estimates as vertical dashed lines\n"
            "    for motif in MOTIFS:\n"
            "        m_row = mu_df[(mu_df['size'] == size) & (mu_df['motif'] == motif)].iloc[0]\n"
            "        if np.isfinite(m_row['mu_point']) and m_row['mu_point'] < RIGHT_CENSOR_STEP - 1:\n"
            "            ax.axvline(m_row['mu_point'], color=SIZE_COLOR[size],\n"
            "                       linestyle=':', alpha=0.3)\n"
            "\n"
            "    # Bottom row: score-weighted centroid\n"
            "    ax = axes[1, col]\n"
            "    for motif in MOTIFS:\n"
            "        traj = depth_traj[size][motif]\n"
            "        valid = traj.dropna(subset=['weighted_norm_depth'])\n"
            "        ax.plot(valid['step'], valid['weighted_norm_depth'],\n"
            "                marker=MOTIF_MARKER[motif], linestyle=MOTIF_LINESTYLE[motif],\n"
            "                color=SIZE_COLOR[size], alpha=0.8, label=motif, markersize=4)\n"
            "    ax.set_xscale('symlog', linthresh=100)\n"
            "    ax.set_xlim(100, 150000)\n"
            "    ax.set_ylim(-0.05, 1.05)\n"
            "    ax.set_xlabel('training step (symlog)')\n"
            "    ax.set_title(f'Pythia-{size}: score-weighted centroid depth')\n"
            "    if col == 0:\n"
            "        ax.set_ylabel('weighted normalized depth')\n"
            "    ax.grid(alpha=0.3)\n"
            "    if col == len(SIZES) - 1:\n"
            "        ax.legend(fontsize=9, loc='upper left')\n"
            "fig.suptitle('Layer depth of each motif across training '\n"
            "             '(induction ▲ dashed / successor ■ dot-dash / S-inhibition ● solid)', y=1.0)\n"
            "plt.tight_layout()\n"
            "plt.show()"
        ),
        md(
            "Reading the plot: each curve traces the layer the *top-scoring* "
            "head of that motif sits at, at each training checkpoint. The "
            "top row shows the strict argmax (sensitive to single-cell noise "
            "but easy to interpret). The bottom row shows the score-weighted "
            "centroid, which is more robust to identity switches — when a "
            "head's score drops and another head takes over, the weighted "
            "centroid moves smoothly while the top-head curve jumps.\n"
            "\n"
            "**Pre-emergence cells (where the motif hasn't fired yet) "
            "produce noisy depth estimates** because the \"top head\" is "
            "essentially the largest noise spike. The faint vertical dashed "
            "lines mark each motif's emergence step μ; reading depth values "
            "to the *right* of those lines is the meaningful interpretation."
        ),
        code(
            "# Final-checkpoint snapshot table for the cross-motif depth comparison\n"
            "rows = []\n"
            "for size in SIZES:\n"
            "    for motif in MOTIFS:\n"
            "        traj = depth_traj[size][motif]\n"
            "        last = traj[traj['step'] == 143000]\n"
            "        if last.empty:\n"
            "            continue\n"
            "        rows.append(dict(\n"
            "            size=size, motif=motif,\n"
            "            top_norm_depth=float(last['top_norm_depth'].iloc[0]),\n"
            "            weighted_norm_depth=float(last['weighted_norm_depth'].iloc[0]),\n"
            "        ))\n"
            "depth_summary = pd.DataFrame(rows)\n"
            "wide = depth_summary.pivot(index='size', columns='motif',\n"
            "                            values=['top_norm_depth', 'weighted_norm_depth'])\n"
            "print('Final-checkpoint normalized depth per (size, motif):')\n"
            "print(wide.to_string(float_format=lambda v: f'{v:.3f}'))"
        ),
        md(
            "## Sub-deliverable 3 — Bootstrap reversal rate per (size, pair)\n"
            "\n"
            "**Reframe of the originally-registered \"per-pair descriptive p-values.\"** The original sub-deliverable computed `0.5 if holds else 1.0` from the point estimates — i.e., the *prior probability* of the observed ordering under exchangeable H_0, dressed as a p-value. That is not a p-value: it is constant by construction within {holds, fails}.\n"
            "\n"
            "Replaced here with the **bootstrap reversal rate**: across the B=1000 per-prompt bootstrap replicates already computed in sub-deliverable 2, what fraction of replicates show the predicted ordering *fail*? This is a real magnitude-aware summary of how robust each per-size pair-ordering is to per-prompt resampling. Censored ties (both μ at the right-censor sentinel) are counted as undetermined per §H2-4 ties-fail and treated as not-holding.\n"
            "\n"
            "Reading the table:\n"
            "- `reversal_rate ≈ 0`: ordering robustly holds across resamples.\n"
            "- `reversal_rate ≈ 0.5`: bootstrap is split — ordering at the point estimate is essentially coincidence given prompt sampling.\n"
            "- `reversal_rate ≈ 1`: ordering robustly fails (or is undetermined under censored ties).\n"
            "\n"
            "Critical for the reframe: the joint sign-test pass in sub-deliverable 1 is a 1-bit-per-size existence claim. The reversal rate is the magnitude-aware companion that surfaces *which* per-size legs of the joint claim are propped up by signal versus by point-estimate happenstance."
        ),
        code(
            "from src.analysis.phase2_bootstrap import bootstrap_pair_reversal_rate\n"
            "\n"
            "PAIRS = [\n"
            "    ('induction', 'successor', 'induction → successor'),\n"
            "    ('successor', 's_inhibition', 'successor → S-inhibition'),\n"
            "    ('induction', 's_inhibition', 'induction → S-inhibition (transitive)'),\n"
            "]\n"
            "\n"
            "rows = []\n"
            "for size in SIZES:\n"
            "    for early_motif, late_motif, label in PAIRS:\n"
            "        result = bootstrap_pair_reversal_rate(\n"
            "            mus_early=bootstrap_mus[(size, early_motif)],\n"
            "            mus_late=bootstrap_mus[(size, late_motif)],\n"
            "            size=size,\n"
            "            motif_early=early_motif,\n"
            "            motif_late=late_motif,\n"
            "        )\n"
            "        rows.append(dict(\n"
            "            size=size,\n"
            "            pair=label,\n"
            "            n_total=result.n_total,\n"
            "            n_holds=result.n_holds,\n"
            "            n_undetermined=result.n_undetermined,\n"
            "            holds_rate=result.holds_rate,\n"
            "            reversal_rate=result.reversal_rate,\n"
            "        ))\n"
            "reversal_df = pd.DataFrame(rows)\n"
            "print('Bootstrap reversal rate per (size, pair) — B=1000 per-prompt resamples:')\n"
            "print(reversal_df.to_string(index=False, float_format=lambda v: f'{v:.3f}'))"
        ),
        md(
            "## What the reversal-rate table says (interpretation guide)\n"
            "\n"
            "Look for three patterns:\n"
            "\n"
            "**Pattern A — robust ordering:** `holds_rate ≈ 1.0`, `reversal_rate ≈ 0.0`. The pair-ordering at this size is propped up by signal that survives per-prompt resampling. This is the strong form of evidence for the registered ordering.\n"
            "\n"
            "**Pattern B — censored vacuous ordering:** `n_undetermined > 0` and `holds_rate < 1`. One or both motifs are right-censored at step143000 in many bootstrap replicates. The point estimate satisfies the inequality only because the later motif failed to emerge — the ordering is mechanically true but not *informative*.\n"
            "\n"
            "**Pattern C — split bootstrap:** `holds_rate ≈ 0.5-0.7`. The sign of the per-prompt bootstrap estimate of (μ_late − μ_early) flips substantially across replicates. The point-estimate pass survived the gate but is fragile.\n"
            "\n"
            "We expect to see Pattern A for 410m's (induction, successor) leg, and Pattern B/C contamination for the 70m S-inhibition leg and 160m S-inhibition leg. This is the central evidence for the §H2-9-R reframe."
        ),
        md(
            "## Sub-deliverable 5 — Major differences between the three head types\n"
            "\n"
            "Cross-motif comparison of structural properties at the final "
            "checkpoint (step143000) per Pythia size. Four properties:\n"
            "\n"
            "- **Depth**: top-head normalized layer (layer / (n_layers - 1)).\n"
            "- **Count saturation**: number of heads passing threshold at step143000.\n"
            "- **Score magnitude**: max score per cell.\n"
            "- **Identity stability**: fraction of step143000 top-3 heads also in top-3 at step25000."
        ),
        code(
            "rows = []\n"
            "for size in SIZES:\n"
            "    for motif, df, threshold, comparator in [\n"
            "        ('induction', df_ind, INDUCTION_THRESHOLD, 'gt'),\n"
            "        ('successor', df_suc, TAU_LIFT, 'gte'),\n"
            "        ('s_inhibition', df_si, TAU_STRICT, 'gte'),\n"
            "    ]:\n"
            "        sub = df[(df['size'] == size) & (df['step'] == 143000)]\n"
            "        n_layers = int(sub['layer'].max() + 1)\n"
            "        if comparator == 'gt':\n"
            "            sat = int((sub['score'] > threshold).sum())\n"
            "        else:\n"
            "            sat = int((sub['score'] >= threshold).sum())\n"
            "        max_idx = int(np.argmax(sub['score'].values))\n"
            "        top_layer = int(sub.iloc[max_idx]['layer'])\n"
            "        max_score = float(sub['score'].max())\n"
            "        # Identity stability: top-3 at 143k vs at 25000 (or nearest).\n"
            "        nearest_25k_step = sorted(df[df['size'] == size]['step'].unique(),\n"
            "                                   key=lambda s: abs(s - 25000))[0]\n"
            "        sub_25k = df[(df['size'] == size) & (df['step'] == nearest_25k_step)]\n"
            "        top3_143k = set(map(tuple, sub.nlargest(3, 'score')[['layer', 'head']].values.tolist()))\n"
            "        top3_25k = set(map(tuple, sub_25k.nlargest(3, 'score')[['layer', 'head']].values.tolist()))\n"
            "        stability = len(top3_143k & top3_25k) / 3.0\n"
            "        rows.append(dict(\n"
            "            size=size, motif=motif,\n"
            "            top_norm_depth=top_layer / max(n_layers - 1, 1),\n"
            "            count_at_saturation=sat,\n"
            "            max_score=max_score,\n"
            "            identity_stability_25k_to_143k=stability,\n"
            "        ))\n"
            "diff_df = pd.DataFrame(rows)\n"
            "print(diff_df.to_string(index=False, float_format=lambda v: f'{v:.3f}'))"
        ),
        md(
            "## Sub-deliverable 6 — Threshold-sensitivity check (B=1000)\n"
            "\n"
            "Vary each motif's locked threshold by ± 25% in 5 increments per §H2-2. At each variant, run the full **B=1000 per-prompt bootstrap** (not B=1 as in earlier drafts) and report both the μ point estimate and the 95% percentile bootstrap CI. The CI envelope is the panel's stochastic-variation reading; the point-estimate curve answers \"does the registered ordering survive plausible threshold mis-specification?\"\n"
            "\n"
            "This panel is *expensive* — 5 thresholds × 3 motifs × 3 sizes × 1000 bootstraps. Cell takes a few minutes."
        ),
        code(
            "rng = np.random.default_rng(2)\n"
            "sens_rows = []\n"
            "for size in SIZES:\n"
            "    for motif, df, threshold, comparator in [\n"
            "        ('induction', df_ind, INDUCTION_THRESHOLD, 'gt'),\n"
            "        ('successor', df_suc, TAU_LIFT, 'gte'),\n"
            "        ('s_inhibition', df_si, TAU_STRICT, 'gte'),\n"
            "    ]:\n"
            "        steps, _ = per_size_curve(df, size, threshold, comparator)\n"
            "        # Pre-load per-prompt arrays once per (size, motif), reuse across thresholds\n"
            "        cache_dir = REPO / 'data' / 'exploration'\n"
            "        if motif == 'induction':\n"
            "            per = {int(s): np.load(per_cell_dir('induction', size) / f'{size}_step{s}.npz')['per_sequence_scores'] for s in steps}\n"
            "            si_extras = None\n"
            "        elif motif == 'successor':\n"
            "            per = {}\n"
            "            for s in steps:\n"
            "                npz = np.load(per_cell_dir('successor', size) / f'{size}_step{s}.npz')\n"
            "                per[int(s)] = {'real': npz['per_prompt_real'], 'null': npz['per_prompt_null'], 'cats': npz['prompt_categories']}\n"
            "            si_extras = None\n"
            "        else:\n"
            "            per = {}; nm_layers = {}\n"
            "            for s in steps:\n"
            "                npz = np.load(per_cell_dir('s_inhibition', size) / f'{size}_step{s}.npz')\n"
            "                per[int(s)] = npz['per_prompt_delta']; nm_layers[int(s)] = npz['nm_heads'][:, 0].tolist()\n"
            "            a_grp = df_si[(df_si['size'] == size) & (df_si['step'] == steps[0])]\n"
            "            n_layers = int(a_grp['layer'].max() + 1); n_heads = int(a_grp['head'].max() + 1)\n"
            "            sender_layers = np.array([L for L in range(n_layers) for _ in range(n_heads)])\n"
            "            si_extras = (nm_layers, sender_layers)\n"
            "        for frac in THRESHOLD_SENSITIVITY_FRACTIONS:\n"
            "            thr = threshold * (1.0 + frac)\n"
            "            if motif == 'induction':\n"
            "                mus, mu_point = bootstrap_induction(per, thr, rng, B=1000)\n"
            "            elif motif == 'successor':\n"
            "                mus, mu_point = bootstrap_successor(per, thr, rng, B=1000)\n"
            "            else:\n"
            "                nm_layers_d, sender_layers_arr = si_extras\n"
            "                mus, mu_point = bootstrap_s_inhibition(per, thr, nm_layers_d, sender_layers_arr, rng, B=1000)\n"
            "            bres = summarize_bootstrap(size, motif, thr, mus, mu_point)\n"
            "            sens_rows.append(dict(\n"
            "                size=size, motif=motif, threshold=thr, fraction=frac,\n"
            "                mu_point=mu_point,\n"
            "                ci_low=bres.mu_ci_low, ci_high=bres.mu_ci_high,\n"
            "            ))\n"
            "        print(f'  done: {size}, {motif}')\n"
            "sens_df = pd.DataFrame(sens_rows)\n"
            "\n"
            "fig, axes = plt.subplots(1, len(SIZES), figsize=(6 * len(SIZES), 5), sharey=False)\n"
            "for ax, size in zip(axes, SIZES):\n"
            "    for motif in MOTIFS:\n"
            "        sub = sens_df[(sens_df['size'] == size) & (sens_df['motif'] == motif)].sort_values('threshold')\n"
            "        # Bootstrap envelope (95% CI)\n"
            "        ax.fill_between(sub['fraction'] * 100, sub['ci_low'], sub['ci_high'],\n"
            "                        color=SIZE_COLOR[size], alpha=0.15)\n"
            "        # Point estimate\n"
            "        ax.plot(sub['fraction'] * 100, sub['mu_point'], marker=MOTIF_MARKER[motif],\n"
            "                color=SIZE_COLOR[size], alpha=0.85,\n"
            "                linestyle=MOTIF_LINESTYLE[motif], label=motif)\n"
            "    ax.axvline(0, color='gray', linestyle='--', alpha=0.5)\n"
            "    ax.set_yscale('symlog', linthresh=1)\n"
            "    ax.set_xlabel('threshold variation (%)')\n"
            "    if size == SIZES[0]:\n"
            "        ax.set_ylabel('emergence step μ (point + 95% bootstrap CI envelope)')\n"
            "    ax.set_title(f'Pythia-{size}')\n"
            "    ax.legend(fontsize=8)\n"
            "    ax.grid(alpha=0.3)\n"
            "fig.suptitle('Threshold-sensitivity: μ vs ± 25% threshold variation, with B=1000 bootstrap envelope', y=1.02)\n"
            "plt.tight_layout()\n"
            "plt.show()"
        ),
        md(
            "## Power analysis: μ-uncertainty floor as a function of max_count (post-hoc, §H2-9-R)\n"
            "\n"
            "A reviewer concern about the marginal regime: with `max_count = 3`, the logistic fit is essentially three points above zero, which can be fit by many curves with widely-varying μ. **Why should we trust μ_point to within an order of magnitude when L_true ≈ 3?**\n"
            "\n"
            "We answer this empirically. Simulate logistic emergence with a known true μ, fit it under the observation noise, and report the recovered-μ spread as a function of the saturation level (max_count). Below `max_count = 3`, the recovered μ has an uncertainty floor of roughly an order of magnitude — which is exactly what the bootstrap CIs in sub-deliverable 2 are showing for the marginal cells.\n"
            "\n"
            "This is a sensitivity analysis that quantifies the prior intuition: *small head populations carry weak emergence-step information.* The reframe in sub-deliverable 7 leans on this — a marginal cell is not a confirmation of a clean emergence step; it is a confirmation that a small population starts to satisfy the threshold somewhere in a wide window."
        ),
        code(
            "from src.analysis.phase2_logistic import fit_logistic_to_counts\n"
            "\n"
            "def simulate_recovery(L_true, mu_true=8000.0, k_true=2.0, n_trials=200, rng=None):\n"
            "    \"\"\"Simulate Poisson-noise observation of a logistic curve.\n"
            "\n"
            "    Returns array of recovered μ values under repeated sampling.\n"
            "    \"\"\"\n"
            "    if rng is None:\n"
            "        rng = np.random.default_rng(7)\n"
            "    sim_steps = np.array([int(s) for s in df_ind.step.unique()], dtype=np.int64)\n"
            "    sim_steps = np.sort(sim_steps)\n"
            "    log_steps = np.log(np.maximum(sim_steps.astype(float), 0.5))\n"
            "    true_curve = L_true / (1.0 + np.exp(-k_true * (log_steps - np.log(mu_true))))\n"
            "    recovered = []\n"
            "    for _ in range(n_trials):\n"
            "        observed = rng.poisson(true_curve)\n"
            "        if observed.max() < 2:\n"
            "            continue  # would be censored under §H2-3 rules\n"
            "        try:\n"
            "            _, _, mu_hat = fit_logistic_to_counts(sim_steps, observed)\n"
            "        except Exception:\n"
            "            continue\n"
            "        if np.isfinite(mu_hat):\n"
            "            recovered.append(mu_hat)\n"
            "    return np.array(recovered)\n"
            "\n"
            "L_VALUES = [1, 2, 3, 5, 10, 20]\n"
            "rng = np.random.default_rng(7)\n"
            "power_rows = []\n"
            "for L in L_VALUES:\n"
            "    rec = simulate_recovery(L, rng=rng)\n"
            "    if rec.size == 0:\n"
            "        power_rows.append(dict(L_true=L, n_recovered=0, mu_median=float('nan'),\n"
            "                                mu_p05=float('nan'), mu_p95=float('nan'),\n"
            "                                ratio_p95_over_p05=float('nan')))\n"
            "        continue\n"
            "    p05, p50, p95 = np.percentile(rec, [5, 50, 95])\n"
            "    power_rows.append(dict(\n"
            "        L_true=L, n_recovered=int(rec.size),\n"
            "        mu_median=float(p50), mu_p05=float(p05), mu_p95=float(p95),\n"
            "        ratio_p95_over_p05=float(p95 / max(p05, 1.0)),\n"
            "    ))\n"
            "power_df = pd.DataFrame(power_rows)\n"
            "print('Power analysis: μ-recovery as function of L_true (true peak count).')\n"
            "print('  Underlying μ_true = 8000 steps, k_true = 2.0, Poisson noise on per-step counts.')\n"
            "print('  ratio_p95_over_p05 < 2 = good, > 5 = unusable for ordering.')\n"
            "print(power_df.to_string(index=False, float_format=lambda v: f'{v:.0f}' if v == int(v) else f'{v:.2f}'))"
        ),
        code(
            "fig, ax = plt.subplots(figsize=(8, 5))\n"
            "valid = power_df.dropna(subset=['mu_p05', 'mu_p95', 'mu_median'])\n"
            "ax.fill_between(valid['L_true'], valid['mu_p05'], valid['mu_p95'],\n"
            "                color='tab:gray', alpha=0.3, label='5%-95% recovery range')\n"
            "ax.plot(valid['L_true'], valid['mu_median'], marker='o', color='tab:red',\n"
            "        label='median recovered μ')\n"
            "ax.axhline(8000, color='tab:green', linestyle='--', label='true μ = 8000')\n"
            "ax.set_xlabel('L_true (true peak count of motif heads)')\n"
            "ax.set_ylabel('recovered μ (steps)')\n"
            "ax.set_yscale('symlog', linthresh=10)\n"
            "ax.set_title('μ-recovery uncertainty vs head-count saturation\\n(simulation; Poisson noise on logistic emergence curve)')\n"
            "ax.grid(alpha=0.3)\n"
            "ax.legend()\n"
            "plt.tight_layout()\n"
            "plt.show()"
        ),
        md(
            "**Reading the figure.** The horizontal green line is the true emergence step; the red dot is the median recovered μ; the gray band is the 5%-95% recovery range under repeated noisy observation of the same underlying curve.\n"
            "\n"
            "At `L_true ≥ 5` (the §H2-3 \"emerged\" threshold), the recovery range is narrow — μ is well-determined within ~ ± 30%.\n"
            "\n"
            "At `L_true ∈ {2, 3}` (the §H2-3 \"marginal\" regime), the recovery range spans roughly an order of magnitude. **This is consistent with the bootstrap CI we observe at 70m successor (max_count=2) and 160m S-inhibition (max_count=3).** The marginal cells in sub-deliverable 2 are not anomalously poorly-fit; they are at the prior-information floor for a 3-point logistic fit.\n"
            "\n"
            "At `L_true = 1`, the §H2-3 censored regime applies and the bootstrap-median fallback is used per §H2-3. The simulation here is a sanity check that the §H2-3 tiered handling rule is calibrated correctly.\n"
            "\n"
            "**Implication for the H1-C verdict.** The 70m S-inhibition leg is censored. The 160m S-inhibition leg has L=3, putting its μ-uncertainty at the order-of-magnitude floor identified here. Interpreting these legs as confirmations of a precise μ value would be over-reading the data. The reframe in sub-deliverable 7 explicitly de-emphasizes them in the per-size verdict."
        ),
        md(
            "## Sub-deliverable 7 — Verdict (reframed per §H2-9-R)\n"
            "\n"
            "### What the registered gate says\n"
            "\n"
            "Mechanically: the joint sign test passes with p ≈ 0.00463 < 0.005. Per HYPOTHESIS.md §3 falsification criterion, **the registered H1-C is not falsified.** This statement is correct and we don't soften it.\n"
            "\n"
            "### What the registered gate does NOT say\n"
            "\n"
            "The joint sign test is a 3-bit observation: `(holds_70m, holds_160m, holds_410m)`. Under exchangeable per-size H_0 (each size's three-motif ordering is uniform over 6 permutations), the probability of `(True, True, True)` is (1/6)³ ≈ 0.00463. That is the right p-value for the right null. It is *not* a continuous magnitude-of-evidence statistic and was never intended to be one.\n"
            "\n"
            "Two readings of the gate pass are admissible:\n"
            "\n"
            "1. *(Registered)* The pre-registered ordering hypothesis is supported across three Pythia sizes at the registered alpha. The compositional account that motivated the prediction is consistent with the Phase 2 sweep.\n"
            "2. *(Reframed, §H2-9-R)* The 3-bit pass survives only if you accept censored cells as legitimate \"holds\" against any earlier-emerging motif. With 4/9 cells right-censored or marginal at the upper sentinel, the gate is structurally sensitive to the tiered-fit rule (§H2-3) that elevates `did not emerge during training` to a numerically-larger μ.\n"
            "\n"
            "We register reading (2) as the headline interpretation of Phase 2.\n"
            "\n"
            "### What we actually claim\n"
            "\n"
            "**Robust per-size confirmation:** Pythia-410m only. Both ordering pairs (induction → successor, successor → S-inhibition) emerge with well-fit μ values, low bootstrap reversal rate, and CI separation visible in sub-deliverable 4.\n"
            "\n"
            "**Marginal per-size confirmation:** Pythia-160m. Induction and successor μ are well-fit; S-inhibition's logistic fit hits the upper bound (μ_point = 2,000,000), the bootstrap CI overlaps successor's CI, and the (successor, S-inhibition) pair-ordering is propped up by a marginal regime fit rather than signal.\n"
            "\n"
            "**Censored confirmation:** Pythia-70m. S-inhibition does not emerge during training (max_count = 1 head at step143000); the (successor, S-inhibition) pair satisfies μ_suc < μ_si only because S-inhibition is right-censored at step143000 by §H2-3. This is *vacuous* satisfaction in a strict sense and is the central evidence for scale-dependent emergence of S-inhibition.\n"
            "\n"
            "**Scale-dependence finding (new headline):** S-inhibition's emergence appears scale-dependent in Pythia. It does not emerge at 70m, emerges marginally at 160m, and emerges with a clean fit at 410m. Induction and successor emerge at all three sizes. This is the most reportable Phase 2 finding.\n"
            "\n"
            "**Depth-vs-temporal asymmetry (sub-deliverable 4b):** in 160m and 410m, successor heads sit at *deeper* normalized layer depth than S-inhibition heads. Information flows shallow → deep, so S-inhibition cannot be reading from successor's output if it lives architecturally upstream. The temporal emergence ordering does not, on the current evidence, reflect a compositional architectural ordering. This is reported as a substantive finding distinct from the registered hypothesis.\n"
            "\n"
            "**Identity stability:** Top-3 successor and S-inhibition heads turn over substantially between step25k and step143k (stability 0.0–0.667 across sizes; sub-deliverable 5). The \"emergence step\" abstraction is therefore tracking a count of heads above threshold, not a stable named circuit.\n"
            "\n"
            "### What this paper should be\n"
            "\n"
            "A scale-dependent emergence study with one robust per-size confirmation (410m), interpreted alongside three orthogonal findings (depth ≠ temporal, identity churn, scale dependence of S-inhibition). The registered joint sign test passes; we treat that pass as a necessary-but-not-sufficient milestone, with the Phase 3 / writeup work foregrounding the magnitude-aware findings."
        ),
        code(
            "print('=' * 70)\n"
            "print(' Registered H1-C joint sign test')\n"
            "print('=' * 70)\n"
            "print(f'  n_sizes_holding (sign test): {verdict.n_sizes_holding}/3')\n"
            "print(f'  joint p under exchangeable H_0: {verdict.joint_p_under_h0}')\n"
            "print(f'  registered gate p < 0.005: {\"PASS\" if verdict.passes else \"FAIL\"}')\n"
            "print()\n"
            "print('=' * 70)\n"
            "print(' Reframed per-size verdict (§H2-9-R)')\n"
            "print('=' * 70)\n"
            "for o in orderings:\n"
            "    sub = mu_df[mu_df['size'] == o.size]\n"
            "    regimes = dict(zip(sub['motif'], sub['regime']))\n"
            "    label_parts = []\n"
            "    for m in MOTIFS:\n"
            "        label_parts.append(f'{m}={regimes.get(m, \"?\")}')\n"
            "    regime_str = ', '.join(label_parts)\n"
            "    if all(regimes.get(m) == 'emerged' for m in MOTIFS):\n"
            "        cls = 'ROBUST'\n"
            "    elif any(regimes.get(m) == 'censored' for m in MOTIFS):\n"
            "        cls = 'CENSORED (vacuous against censored motif)'\n"
            "    else:\n"
            "        cls = 'MARGINAL'\n"
            "    print(f'  Pythia-{o.size}: {cls} -- regimes: {regime_str}')\n"
            "print()\n"
            "print('Headline finding: scale-dependent emergence of S-inhibition.')\n"
            "print('Robust ordering confirmation: 410m only.')\n"
            "print('Depth ≠ temporal: S-inhibition lives architecturally upstream of successor in 160m/410m.')\n"
            "print('See sub-deliverables 3, 4b, 5 for the supporting magnitude-aware analyses.')"
        ),
        # ============================================================
        # §H3-scale extension (Phase 3 1B scale-extension)
        # Sub-deliverables (i)-(vii) per HYPOTHESIS.md §H3-scale-8.
        # ============================================================
        md(
            "---\n"
            "\n"
            "## §H3-scale verdict — Pythia-1B scale-extension gate\n"
            "\n"
            "Pre-registered in HYPOTHESIS.md §H3-scale (committed before any 1B compute). "
            "Separate gate from the §H1-C / §H2-5 joint test above; that test passed at "
            "p = 0.00463 across the 3 registered sizes and is unchanged. §H3-scale "
            "forward-tests the §H2-9-R reframe at 1B with a 5-leg conjunctive gate.\n"
            "\n"
            "**Gate (§H3-scale-4):** (A.i) `max_count_si^1B ≥ 5`, (A.ii) "
            "`P(μ_si^1B < μ_si^410m) ≥ 0.95`, (A.iii) within-1B disjoint CI on "
            "`μ_si^1B` vs `μ_suc^1B`, (B.i) all 3 motifs full-fit at 1B, (B.ii) strict "
            "ordering `μ_ind^1B < μ_suc^1B < μ_si^1B`. **Failure-mode taxonomy** "
            "(§H3-scale-6) priority: TOOLING > REGR > ORD-BREAK > WIDE-CI > SAT > PASS."
        ),
        code(
            "# Load pre-computed §H3-scale artifacts from `_run_phase3_1b_analysis.py`.\n"
            "verdict_df = pd.read_parquet(REPO / 'data' / 'exploration' / 'phase3_1b_h3scale_verdict.parquet')\n"
            "mus4_npz = np.load(REPO / 'data' / 'exploration' / 'phase3_1b_bootstrap_mus.npz')\n"
            "\n"
            "print('=' * 70)\n"
            "print(' §H3-scale gate verdict (HYPOTHESIS.md §H3-scale-4)')\n"
            "print('=' * 70)\n"
            "for _, r in verdict_df.iterrows():\n"
            "    if r['leg'] in ('JOINT', 'PATTERN'):\n"
            "        continue\n"
            "    flag = 'PASS' if r['pass_'] else 'FAIL'\n"
            "    print(f'  ({r[\"leg\"]:<5s}) {flag}  value={r[\"value\"]:<12s} requirement: {r[\"requirement\"]}')\n"
            "joint_row = verdict_df[verdict_df['leg'] == 'JOINT'].iloc[0]\n"
            "pattern_row = verdict_df[verdict_df['leg'] == 'PATTERN'].iloc[0]\n"
            "print()\n"
            "print(f'Joint gate (5/5 legs): {\"PASS\" if joint_row[\"pass_\"] else \"FAIL\"} '\n"
            "      f'({joint_row[\"value\"]}/5 legs hold)')\n"
            "print(f'Matched §H3-scale-6 pattern: {pattern_row[\"value\"]}')"
        ),
        md(
            "### Bootstrap reversal-rate `P(μ_si^X < μ_si^410m)`\n"
            "\n"
            "Direct test of (A.ii). Across B = 1000 paired per-prompt bootstraps, "
            "what fraction shows `μ_si^X < μ_si^410m`? At 1B, the gate threshold is "
            "≥ 0.95. Reported across all 4 sizes (vs 410m baseline) for cross-size "
            "scale-dependence context.\n"
            "\n"
            "- `rate ≈ 1.0`: S-inhibition emerges robustly *earlier* at this size than at 410m.\n"
            "- `rate ≈ 0.5`: bootstrap split — timing indistinguishable.\n"
            "- `rate ≈ 0.0`: S-inhibition emerges later at this size."
        ),
        code(
            "rev_rows = []\n"
            "mus_410m = mus4_npz['410m_s_inhibition']\n"
            "for size in SIZES:\n"
            "    if size == '410m':\n"
            "        continue\n"
            "    mus = mus4_npz[f'{size}_s_inhibition']\n"
            "    mask = np.isfinite(mus) & np.isfinite(mus_410m)\n"
            "    rate = float((mus[mask] < mus_410m[mask]).mean()) if mask.sum() else float('nan')\n"
            "    rev_rows.append(dict(size=size, n_paired=int(mask.sum()), reversal_rate_lt=rate))\n"
            "rev_df = pd.DataFrame(rev_rows)\n"
            "print('P(μ_si^X < μ_si^410m) across sizes vs 410m baseline:')\n"
            "print(rev_df.to_string(index=False, float_format=lambda v: f'{v:.3f}'))"
        ),
        md(
            "### Within-1B CI-separation diagnostic\n"
            "\n"
            "(A.iii) requires the 95% bootstrap CI on `μ_si^1B` to lie strictly *above* "
            "the CI on `μ_suc^1B`. The actual ordering observed at 1B is the opposite: "
            "S-inhibition emerges *before* successor."
        ),
        code(
            "row_si = mu_df[(mu_df['size'] == '1b') & (mu_df['motif'] == 's_inhibition')].iloc[0]\n"
            "row_suc = mu_df[(mu_df['size'] == '1b') & (mu_df['motif'] == 'successor')].iloc[0]\n"
            "row_ind = mu_df[(mu_df['size'] == '1b') & (mu_df['motif'] == 'induction')].iloc[0]\n"
            "fig, ax = plt.subplots(figsize=(10, 3))\n"
            "for label, r, c in [('induction', row_ind, 'tab:blue'),\n"
            "                    ('successor', row_suc, 'tab:green'),\n"
            "                    ('s_inhibition', row_si, 'tab:red')]:\n"
            "    ax.errorbar([r['mu_point']], [label],\n"
            "                xerr=[[r['mu_point'] - r['ci_low']], [r['ci_high'] - r['mu_point']]],\n"
            "                fmt='o', color=c, capsize=6, label=f'{label}: μ={r[\"mu_point\"]:.0f}')\n"
            "ax.set_xscale('symlog', linthresh=100)\n"
            "ax.set_xlim(100, 150000)\n"
            "ax.set_xlabel('μ (training step, symlog) with 95% bootstrap CI')\n"
            "ax.set_title('Pythia-1B: per-motif μ with bootstrap CIs (§H3-scale (A.iii) diagnostic)')\n"
            "ax.grid(alpha=0.3)\n"
            "ax.legend(fontsize=9, loc='upper right')\n"
            "plt.tight_layout()\n"
            "plt.show()\n"
            "\n"
            "print(f'\\nμ_si^1B  CI = [{row_si[\"ci_low\"]:.0f}, {row_si[\"ci_high\"]:.0f}]')\n"
            "print(f'μ_suc^1B CI = [{row_suc[\"ci_low\"]:.0f}, {row_suc[\"ci_high\"]:.0f}]')\n"
            "if row_si['ci_high'] < row_suc['ci_low']:\n"
            "    print('CIs disjoint with μ_si BELOW μ_suc — H1-C ordering reverses at 1B.')\n"
            "elif row_si['ci_low'] > row_suc['ci_high']:\n"
            "    print('CIs disjoint with μ_si ABOVE μ_suc — (A.iii) PASSES.')\n"
            "else:\n"
            "    print('CIs overlap.')"
        ),
        md(
            "### 1B anchor-inspection diagnostic table\n"
            "\n"
            "Pre-sweep anchor inspection at Pythia-1B-deduped @ step143000 (§H3-scale-5). "
            "All three anchors PASSED on both gates, no TOOLING-pattern detector "
            "breakage at d_model = 2048."
        ),
        code(
            "anchor_rows = [\n"
            "    dict(motif='induction', detector='Olsson prefix-match',\n"
            "         threshold='> 0.3 (brief §4)',\n"
            "         heads_clearing=9, top_head='L4H4 score=0.9334',\n"
            "         numerical_gate='PASS', second_gate='(N/A)'),\n"
            "    dict(motif='successor', detector='§SU-1b lift-form cross-cat DLA',\n"
            "         threshold='≥ 0.13496 (§SU-tau)',\n"
            "         heads_clearing=12, top_head='L11H6 lift=+3.0308',\n"
            "         numerical_gate='PASS', second_gate='qualitative PASS (4/4 cats positive)'),\n"
            "    dict(motif='s_inhibition', detector='§S-1 path-patching Δ_h',\n"
            "         threshold='≥ 0.0372 (§S-tau)',\n"
            "         heads_clearing=1, top_head='L8H7 Δ_h=+0.0692',\n"
            "         numerical_gate='PASS', second_gate='mechanistic PASS (4/4 NMs positive)'),\n"
            "]\n"
            "anchor_df = pd.DataFrame(anchor_rows)\n"
            "print('Pythia-1B anchor inspection (§H3-scale-5):')\n"
            "print(anchor_df.to_string(index=False))"
        ),
        md(
            "### Matched paper-headline string\n"
            "\n"
            "Per §H3-scale-6, the matched headline for the failure-mode pattern is:"
        ),
        code(
            "pattern = pattern_row['value']\n"
            "headlines = {\n"
            "    'PASS': 'Scale-dependent S-inhibition emergence holds across Pythia 70m → 1B.',\n"
            "    'SAT': 'S-inhibition emergence time saturates between 410m and 1B; head count continues to scale.',\n"
            "    'REGR': 'Non-monotonic S-inhibition emergence in Pythia: regression at 1B.',\n"
            "    'ORD-BREAK': 'H1-C ordering is scale-bounded in Pythia: breaks at 1B.',\n"
            "    'WIDE-CI': '1B reproduces 160m\\'s marginal-overlap pattern, not 410m\\'s clean separation; scale-dependence is non-monotonic in CI-axis.',\n"
            "}\n"
            "print(f'§H3-scale-6 matched pattern: {pattern}')\n"
            "print(f'§H3-scale-6 matched headline:')\n"
            "print(f'  {headlines.get(pattern, \"(unmatched)\")}')\n"
            "print()\n"
            "print('Empirical signature observed (for the writeup):')\n"
            "print('  - (A.i) FAIL: count saturation between 410m and 1B (max=3 at both).')\n"
            "print('  - (A.ii) PASS at 1.000: S-inhibition emerges earlier at 1B in 100% of paired bootstraps.')\n"
            "print('  - (A.iii) FAIL: μ_si^1B sits BELOW μ_suc^1B — ordering reversal.')\n"
            "print('  - (B.i) FAIL: S-inhibition in marginal regime (3 heads).')\n"
            "print('  - (B.ii) FAIL: order at 1B is ind < si < suc, not ind < suc < si.')"
        ),
        md(
            "### §H3-scale interpretation note\n"
            "\n"
            "The matched REGR headline does not capture the data fully: the **timing-axis** "
            "scale-dependence is borne out at maximum confidence (P = 1.0), the **count-"
            "axis** saturates between 410m and 1B, and **H1-C ordering breaks at 1B** "
            "because S-inhibition emerges before successor. Per §H3-scale-9, options for "
            "the writeup are (a) strict-reading: report verdict as REGR with the registered "
            "headline; or (b) §S-5c-style supplementary-acceptance amendment that records "
            "the gate FAIL as REGR (preserving pre-reg discipline) and adds a §S-5c-style supplementary-acceptance "
            "section documenting the supplementary evidence with a refined headline. The "
            "amendment decision is deferred to the writeup phase — for now, the registered "
            "REGR verdict stands."
        ),
        # ============================================================
        # §H4-scaling DEFERRED extension (Phase 4 2.8B partial)
        # Per §H4-7-supersede committed 2026-05-08.
        # ============================================================
        md(
            "---\n"
            "\n"
            "## §H4-scaling verdict — Pythia-2.8B head-count-axis test (DEFERRED)\n"
            "\n"
            "Pre-registered in HYPOTHESIS.md §H4-scaling (committed before any 2.8B "
            "compute). The conjunctive gate (A.timing) AND (A.count) operates on "
            "S-inhibition only. Per the §H4-7-supersede amendment (committed "
            "2026-05-08), the 2.8B S-inhibition sweep was halted at 8 of 40 cells "
            "after observing ~57 min/cell (vs ~6 min/cell projection — 10× over "
            "budget; the §H4-7 escape hatch's 2× pause threshold was exceeded by "
            "5×). The gate is therefore **DEFERRED** — neither (A.timing) nor "
            "(A.count) is evaluable from 8 early-training cells (steps 0–64, all "
            "Δ_h ≈ 0).\n"
            "\n"
            "DEFERRED is registered as a sixth §H4-5 pattern at top-of-priority "
            "alongside non-substantive TOOLING: `DEFERRED > TOOLING > NEITHER > "
            "COUNT-ONLY > TIMING-ONLY > PASS`. Track 3's 2.8B leg is parked (under the §writeup-conv-1 convention: Track 3 = Scaling), "
            "not abandoned."
        ),
        code(
            "verdict_partial = pd.read_parquet(\n"
            "    REPO / 'data' / 'exploration' / 'phase4_2_8b_h4scaling_verdict_partial.parquet'\n"
            ")\n"
            "mu_partial = pd.read_parquet(\n"
            "    REPO / 'data' / 'exploration' / 'phase4_2_8b_bootstrap_mu_partial.parquet'\n"
            ")\n"
            "\n"
            "print('=' * 70)\n"
            "print(' §H4-scaling gate verdict (DEFERRED per §H4-7-supersede)')\n"
            "print('=' * 70)\n"
            "for _, r in verdict_partial.iterrows():\n"
            "    print(f'  ({r[\"leg\"]:<8s}) value={r[\"value\"]:<14s} requirement: {r[\"requirement\"]}')\n"
            "print()\n"
            "print('Track 3\\'s 2.8B leg is parked (under §writeup-conv-1 Track-3 = Scaling). Re-attempt requires either a')\n"
            "print('reduced-grid §H4-supersede, accepting the multi-day full-grid')\n"
            "print('wall time, or a different detector primitive — none scheduled.')"
        ),
        md(
            "### Side observations: induction + successor across 5 sizes\n"
            "\n"
            "Per §H4-1, induction and successor are not the substantive §H4 claim — "
            "they saturate \"yes they emerge robustly\" by 410m. Their 5-size "
            "trajectories are reported as supplementary cross-size data, not §H4 "
            "gate inputs. Both motifs at 2.8B completed cleanly:\n"
            "\n"
            "- Induction at 2.8B: **max_count = 48** (highest of all 5 sizes; 4.7% "
            "  of 1024 heads), μ = 2705, emerged regime.\n"
            "- Successor at 2.8B: max_count = 14, μ = 10915, emerged regime.\n"
            "\n"
            "S-inhibition at 2.8B is intentionally absent from these tables (sweep "
            "was halted)."
        ),
        code(
            "table = mu_partial[['size', 'motif', 'regime', 'max_count', 'mu_point', 'mu_ci_low', 'mu_ci_high']].copy()\n"
            "table['size'] = pd.Categorical(table['size'], categories=['70m','160m','410m','1b','2.8b'], ordered=True)\n"
            "table['motif'] = pd.Categorical(table['motif'], categories=['induction','successor'], ordered=True)\n"
            "table = table.sort_values(['motif', 'size']).reset_index(drop=True)\n"
            "print('Cross-size induction + successor (5 sizes, S-inhibition omitted at 2.8B):')\n"
            "print(table.to_string(index=False, float_format=lambda v: f'{v:.0f}' if v == int(v) else f'{v:.2f}'))"
        ),
        md(
            "### Parameter size vs head-count scaling (best-fit line approximation)\n"
            "\n"
            "Side observation: how does max_count of detected heads scale with "
            "parameter size for induction and successor? With 5 data points across "
            "Pythia-70M → 2.8B, fit a linear best-fit line in log(params) space "
            "for each motif.\n"
            "\n"
            "**Caveat**: this is the *parameter-size axis*, NOT the head-count axis "
            "that §H4-scaling argues is the operationally correct one (per §H4 "
            "head-count rationale: 1B has 128 heads, narrower than 410m's 384 — a "
            "head-count regression). Pythia-1B's parameter size is between 410m "
            "and 2.8b but its head count is *less* than 410m's. The fit below uses "
            "parameter size on x to address the user's specific question, but a "
            "head-count-axis fit would be the methodologically primary view."
        ),
        code(
            "PARAMS_M = {'70m': 70, '160m': 162, '410m': 405, '1b': 1004, '2.8b': 2780}\n"
            "HEADS = {'70m': 48, '160m': 144, '410m': 384, '1b': 128, '2.8b': 1024}\n"
            "\n"
            "fig, axes = plt.subplots(1, 2, figsize=(12, 4.5))\n"
            "for ax, motif, color in zip(axes, ['induction', 'successor'], ['tab:blue', 'tab:green']):\n"
            "    sub = mu_partial[mu_partial['motif'] == motif]\n"
            "    xs = np.array([PARAMS_M[s] for s in sub['size']], dtype=float)\n"
            "    ys = np.array(sub['max_count'].values, dtype=float)\n"
            "    log_xs = np.log10(xs)\n"
            "    coef = np.polyfit(log_xs, ys, 1)  # slope, intercept on log_xs vs ys\n"
            "    fit_x = np.logspace(np.log10(xs.min() * 0.8), np.log10(xs.max() * 1.2), 100)\n"
            "    fit_y = coef[0] * np.log10(fit_x) + coef[1]\n"
            "    ax.scatter(xs, ys, s=80, color=color, zorder=3,\n"
            "               label=f'observed (slope = {coef[0]:.2f} heads / decade params)')\n"
            "    for s, x, y in zip(sub['size'], xs, ys):\n"
            "        ax.annotate(f'{s}', (x, y), textcoords='offset points', xytext=(7, 4), fontsize=9)\n"
            "    ax.plot(fit_x, fit_y, '--', color=color, alpha=0.6,\n"
            "            label=f'linear fit on log10(params)')\n"
            "    ax.set_xscale('log')\n"
            "    ax.set_xlabel('parameter size (M)')\n"
            "    ax.set_ylabel(f'max_count of {motif} heads above threshold')\n"
            "    ax.set_title(f'{motif} max_count vs parameter size (5 Pythia sizes)')\n"
            "    ax.grid(alpha=0.3)\n"
            "    ax.legend(fontsize=9, loc='upper left')\n"
            "fig.suptitle('Parameter size vs max_count — side observation, best-fit line on log10(params) axis', y=1.02)\n"
            "plt.tight_layout()\n"
            "plt.show()\n"
            "\n"
            "print('Note: 1B (128 heads) is a head-count regression vs 410m (384 heads).')\n"
            "print('The fit is dominated by the 70m/160m/410m and 2.8b cells; 1B sits below the')\n"
            "print('parameter-axis trend specifically because its architecture is narrower per')\n"
            "print('§H4 rationale. A head-count-axis fit (heads on x) is more interpretable for')\n"
            "print('the §H4-scaling argument; the parameter-axis fit above is reported on user request.')"
        ),
        md(
            "### Total attention heads vs detected heads — §H4-1 head-count-axis view\n"
            "\n"
            "The §H4-1 head-count-axis view: scaling on the **head-count axis**. Total "
            "head counts per size:\n"
            "\n"
            "| size | layers × heads | total |\n"
            "|---|---|---|\n"
            "| 70m | 6 × 8 | **48** |\n"
            "| 160m | 12 × 12 | **144** |\n"
            "| 410m | 24 × 16 | **384** |\n"
            "| 1b | 16 × 8 | **128** ← regression |\n"
            "| 2.8b | 32 × 32 | **1024** |\n"
            "\n"
            "On this axis, 1B sits *between* 70m and 160m by head count, not "
            "between 410m and 2.8b — exactly the §H4 head-count rationale's "
            "claim that 1B is a head-count regression vs 410m."
        ),
        code(
            "TOTAL_HEADS = {'70m': 48, '160m': 144, '410m': 384, '1b': 128, '2.8b': 1024}\n"
            "ordered_by_heads = sorted(['70m', '160m', '410m', '1b', '2.8b'], key=lambda s: TOTAL_HEADS[s])\n"
            "\n"
            "fig, axes = plt.subplots(1, 2, figsize=(12, 4.5))\n"
            "for ax, motif, color in zip(axes, ['induction', 'successor'], ['tab:blue', 'tab:green']):\n"
            "    sub = mu_partial[mu_partial['motif'] == motif]\n"
            "    sub_ordered = sub.set_index('size').loc[ordered_by_heads]\n"
            "    xs = np.array([TOTAL_HEADS[s] for s in ordered_by_heads], dtype=float)\n"
            "    ys = np.array(sub_ordered['max_count'].values, dtype=float)\n"
            "    # Linear best fit: y = m*x + b\n"
            "    slope, intercept = np.polyfit(xs, ys, 1)\n"
            "    y_pred = slope * xs + intercept\n"
            "    ss_res = float(np.sum((ys - y_pred) ** 2))\n"
            "    ss_tot = float(np.sum((ys - ys.mean()) ** 2))\n"
            "    r_squared = 1.0 - ss_res / ss_tot if ss_tot > 0 else float('nan')\n"
            "    fit_x = np.linspace(0, xs.max() * 1.05, 100)\n"
            "    fit_y = slope * fit_x + intercept\n"
            "    fit_eq = f'y = {slope:.4f}x {\"+\" if intercept >= 0 else \"-\"} {abs(intercept):.2f}  (R² = {r_squared:.3f})'\n"
            "    ax.scatter(xs, ys, s=80, color=color, zorder=3, label=f'{motif} max_count')\n"
            "    for s, x, y in zip(ordered_by_heads, xs, ys):\n"
            "        ax.annotate(f'{s}', (x, y), textcoords='offset points', xytext=(7, 4), fontsize=9)\n"
            "    ax.plot(fit_x, fit_y, '--', color=color, alpha=0.6, label=fit_eq, zorder=2)\n"
            "    ax.set_xlabel('total attention heads per model')\n"
            "    ax.set_ylabel(f'max_count of {motif} heads above threshold')\n"
            "    ax.set_title(f'{motif} max_count vs total heads (5 Pythia sizes)')\n"
            "    ax.grid(alpha=0.3)\n"
            "    ax.legend(fontsize=9, loc='upper left')\n"
            "fig.suptitle('Total attention heads vs detected motif heads — §H4-1 head-count-axis head-count axis', y=1.02)\n"
            "plt.tight_layout()\n"
            "plt.show()\n"
            "\n"
            "print('Density (detected / total) per size:')\n"
            "print(f'{\"size\":>5s}  {\"total\":>5s}  {\"ind\":>4s}  {\"ind%\":>5s}  {\"suc\":>4s}  {\"suc%\":>5s}')\n"
            "for s in ordered_by_heads:\n"
            "    th = TOTAL_HEADS[s]\n"
            "    ind_max = int(mu_partial[(mu_partial['size']==s) & (mu_partial['motif']=='induction')]['max_count'].iloc[0])\n"
            "    suc_max = int(mu_partial[(mu_partial['size']==s) & (mu_partial['motif']=='successor')]['max_count'].iloc[0])\n"
            "    print(f'{s:>5s}  {th:>5d}  {ind_max:>4d}  {ind_max/th*100:>4.1f}%  {suc_max:>4d}  {suc_max/th*100:>4.1f}%')"
        ),
        # ============================================================
        # §H4-supersede PASS verdict (Phase 4 2.8B reduced-grid re-attempt)
        # Per §H4-supersede committed 2026-05-10; verdict computed 2026-05-11.
        # The §H4-scaling DEFERRED section above is preserved verbatim for
        # chronology — §H4-supersede exits the DEFERRED state via the
        # registered reduced-grid path.
        # ============================================================
        md(
            "---\n"
            "\n"
            "## §H4-supersede verdict — Pythia-2.8B reduced-grid re-attempt (PASS)\n"
            "\n"
            "Pre-registered in HYPOTHESIS.md §H4-supersede (committed before any §H4-supersede "
            "compute, 2026-05-10). 10-cell S-inhibition sweep on the emergence-likely range "
            "`[5000, 7000, 10000, 14000, 20000, 29000, 41000, 49000, 59000, 70000]`. Gate "
            "predicates inherited **verbatim** from §H4-2 — (A.timing) reversal-rate ≥ 0.95 "
            "AND (A.count) max_count_si^2.8B ≥ 5. Verdict taxonomy inherited verbatim from "
            "§H4-5 + §H4-7-supersede DEFERRED:\n"
            "\n"
            "`DEFERRED > TOOLING > NEITHER > COUNT-ONLY > TIMING-ONLY > PASS`."
        ),
        code(
            "verdict_supersede = pd.read_parquet(\n"
            "    REPO / 'data' / 'exploration' / 'phase4_2_8b_h4supersede_verdict.parquet'\n"
            ").iloc[0]\n"
            "boot_mu = pd.read_parquet(\n"
            "    REPO / 'data' / 'exploration' / 'phase4_2_8b_h4supersede_bootstrap_mu.parquet'\n"
            ")\n"
            "\n"
            "print('=' * 78)\n"
            "print(f'  §H4-supersede VERDICT  →  {verdict_supersede[\"pattern\"]}')\n"
            "print('=' * 78)\n"
            "print(f'  (A.count)  max_count_si^2.8B = {int(verdict_supersede[\"max_count_28b\"])}  (gate ≥ {int(verdict_supersede[\"a_count_gate\"])})  → '\n"
            "      f'{\"PASS\" if verdict_supersede[\"a_count_pass\"] else \"FAIL\"}')\n"
            "print(f'  (A.timing) reversal_rate     = {verdict_supersede[\"reversal_rate\"]:.4f}  '\n"
            "      f'(gate ≥ {verdict_supersede[\"a_timing_gate\"]:.2f})  → '\n"
            "      f'{\"PASS\" if verdict_supersede[\"a_timing_pass\"] else \"FAIL\"}')\n"
            "print()\n"
            "print(f'  μ_si^2.8B (point) = {verdict_supersede[\"mu_28b_point\"]:.1f}')\n"
            "print(f'  μ_si^410m (point) = {verdict_supersede[\"mu_410m_point\"]:.1f}')\n"
            "print(f'  Speedup factor    = {verdict_supersede[\"mu_410m_point\"]/verdict_supersede[\"mu_28b_point\"]:.2f}x')\n"
            "print(f'  Bootstrap         = B={int(verdict_supersede[\"B\"])}, valid={int(verdict_supersede[\"valid\"])}, '\n"
            "      f'fit_fail (2.8B={int(verdict_supersede[\"fit_fail_28b\"])}, 410m={int(verdict_supersede[\"fit_fail_410m\"])})')\n"
            "print()\n"
            "print('  Paper headline:')\n"
            "for line in str(verdict_supersede['paper_headline']).split('. '):\n"
            "    if line.strip(): print(f'    {line.strip()}.')"
        ),
        md(
            "### §H4-supersede 2.8B count-vs-step trajectory (10 cells)"
        ),
        code(
            "df_supersede = pd.read_parquet(\n"
            "    REPO / 'data' / 'exploration' / 'phase4_2_8b_s_inhibition_supersede_sweep.parquet'\n"
            ")\n"
            "TAU_STRICT_28B = 0.0372\n"
            "counts_28b = (df_supersede[df_supersede.score >= TAU_STRICT_28B]\n"
            "              .groupby('step').size()\n"
            "              .reindex(sorted(df_supersede.step.unique()), fill_value=0))\n"
            "\n"
            "print('§H4-supersede 2.8B S-inhibition count vs step (threshold τ_strict = 0.0372):')\n"
            "for step, c in counts_28b.items():\n"
            "    top = df_supersede[df_supersede.step==step].score.max()\n"
            "    bar = '█' * int(c)\n"
            "    print(f'  step{int(step):6d}: count={c:3d}  top Δ_h={top:+.4f}  {bar}')\n"
            "\n"
            "print()\n"
            "print('§writeup-conv-2 caveat: the count crosses ≥ 5 transiently at step 29k')\n"
            "print('and settles at 4 by step 70k (trajectory 1 → 2 → 2 → 3 → 3 → 5 → 4 → 4 → 4 → 4).')\n"
            "print('§H4-2 (A.count) gate is defined on MAX over the grid (not terminal-cell count),')\n"
            "print('so PASS holds as registered. Caveat is disclosed in HYPOTHESIS.md §writeup-conv-2,')\n"
            "print('WRITEUP.md Track 3 section, and here.')"
        ),
        md(
            "### Bootstrap μ distribution (paired 2.8B vs 410m, B = 1000)"
        ),
        code(
            "fig, axes = plt.subplots(1, 2, figsize=(12, 4.5))\n"
            "\n"
            "ax = axes[0]\n"
            "ax.hist(boot_mu['mu_28b'].dropna(), bins=40, alpha=0.6, label='2.8B', color='tab:blue')\n"
            "ax.hist(boot_mu['mu_410m'].dropna(), bins=40, alpha=0.6, label='410m', color='tab:orange')\n"
            "ax.set_xscale('log')\n"
            "ax.set_xlabel('μ_si (training step, log scale)')\n"
            "ax.set_ylabel('bootstrap replicate count')\n"
            "ax.set_title('Bootstrap μ_si distributions — paired B=1000')\n"
            "ax.legend(loc='best')\n"
            "ax.grid(alpha=0.3)\n"
            "\n"
            "ax = axes[1]\n"
            "delta = boot_mu['mu_410m'] - boot_mu['mu_28b']\n"
            "ax.hist(delta.dropna(), bins=40, color='tab:green', alpha=0.7)\n"
            "ax.axvline(0, color='red', lw=1.2, ls='--', label='delta=0 (no acceleration)')\n"
            "ax.set_xlabel('μ_si^410m − μ_si^2.8B (training steps)')\n"
            "ax.set_ylabel('bootstrap replicate count')\n"
            "ax.set_title(f'Paired delta — reversal rate = {float(verdict_supersede[\"reversal_rate\"]):.3f}')\n"
            "ax.legend(loc='best')\n"
            "ax.grid(alpha=0.3)\n"
            "\n"
            "fig.suptitle(f'§H4-supersede (A.timing) bootstrap — verdict: {verdict_supersede[\"pattern\"]}', y=1.02)\n"
            "plt.tight_layout()\n"
            "plt.show()\n"
            "\n"
            "print(f'Reversal rate (P(μ_si^2.8B < μ_si^410m)) = {float(verdict_supersede[\"reversal_rate\"]):.4f}')\n"
            "print(f'Gate: ≥ 0.95 → {\"PASS\" if verdict_supersede[\"a_timing_pass\"] else \"FAIL\"}')"
        ),
        md(
            "### What this means for the paper\n"
            "\n"
            "With §H4-supersede PASS, the project now has three converging tracks (Tracks 1 + "
            "2 + 3) all hitting their pre-registered targets:\n"
            "\n"
            "- **Track 1 (§H1-C):** emergence ordering ind→suc→si holds jointly across 3 "
            "Pythia sizes (p = 0.00463), with §H2-9-R reframe to scale-dependent S-inhibition.\n"
            "- **Track 2 (§H5-causal + §H5-causal-2 + §H5-causal-3):** causal-disjointness of "
            "successor and S-inhibition at inference time is NULL on both metrics at 410m (384 "
            "heads), Metric A NULL at 1B (128 heads, head-count regression — Metric B MIXED "
            "interpreted as narrow-architecture readout artifact), and NULL on both metrics at "
            "2.8B (1024 heads). Scale-stable across head-count tiers 384 + 1024.\n"
            "- **Track 3 (§H4-supersede):** head-count-axis scaling of S-inhibition timing + "
            "count PASSES at 2.8B. μ_si accelerates by ~2.7× from 410m's ~24k to 2.8B's ~9k, "
            "and max_count crosses 5 at step 29k.\n"
            "\n"
            "The §H4-7-supersede DEFERRED chronology (preserved verbatim above) is part of "
            "the audit trail. §H4-supersede exits the DEFERRED state via the registered "
            "reduced-grid path."
        ),
    ]
    return nb


def main() -> None:
    nb = build()
    OUT.parent.mkdir(parents=True, exist_ok=True)
    nbf.write(nb, OUT)
    print(f"Wrote {OUT.relative_to(ROOT)}")


if __name__ == "__main__":
    main()
