"""Build notebooks/h1c_ordering_test.ipynb.

Phase 2 headline deliverable: cross-motif H1-C ordering test (HYPOTHESIS.md
§H2-9 deliverable 4). Loads the three Phase 2 sweep parquets + per-prompt
caches, fits μ_{s,m} with bootstrap CIs, runs the joint H1-C permutation
test, and reports the seven sub-deliverables locked in §H2-9.
"""

from __future__ import annotations

from pathlib import Path

import nbformat as nbf

ROOT = Path(__file__).resolve().parents[1]
OUT = ROOT / "notebooks" / "h1c_ordering_test.ipynb"


def md(text: str) -> nbf.NotebookNode:
    return nbf.v4.new_markdown_cell(text)


def code(src: str) -> nbf.NotebookNode:
    return nbf.v4.new_code_cell(src)


def build() -> nbf.NotebookNode:
    nb = nbf.v4.new_notebook()
    nb["cells"] = [
        md(
            "# H1-C ordering test — joint verdict across 3 motifs × 3 sizes\n"
            "\n"
            "**Phase 2 headline deliverable** (HYPOTHESIS.md §H2-9 deliverable 4).\n"
            "\n"
            "## What this notebook claims (and does not claim)\n"
            "\n"
            "The registered H1-C hypothesis is **μ_induction < μ_successor < μ_S-inhibition** in all three Pythia sizes (70m, 160m, 410m). Under H_0 of exchangeable per-size order, the joint sign test gives p = (1/6)³ ≈ 0.00463; the locked falsification gate is **p < 0.005**.\n"
            "\n"
            "We pass the gate. **We do not, on the strength of that pass alone, claim the registered compositional account is robustly supported.** The joint sign test is a 3-bit observation — for each size, did the predicted strict ordering hold? — and is silent on:\n"
            "\n"
            "1. Whether ordering pairs are supported by *signal* (well-fit μ values with non-overlapping CIs) or by *censoring* (one motif failing to emerge during training, vacuously satisfying the inequality against any earlier motif).\n"
            "2. Whether the temporal ordering reflects a *compositional architectural ordering* in the forward pass, or merely a coincidence of training-time emergence ordering.\n"
            "3. Whether the heads identified as instances of each motif are *stable* across training (i.e., whether \"emergence step\" is a coherent quantity for that motif).\n"
            "\n"
            "Per the reframe registered in HYPOTHESIS.md §H2-9-R: **the headline result is scale-dependent emergence with a single robust per-size confirmation (Pythia-410m).** At 160m, the (successor, S-inhibition) ordering passes only because S-inhibition's logistic fit hits the upper sentinel; the bootstrap CI overlaps successor's CI. At 70m, S-inhibition does not emerge during training (max_count=1, right-censored at step143000), and the ordering passes vacuously. Sub-deliverables 3 (bootstrap reversal rate), 5 (depth-vs-temporal), and 7 (verdict) interpret these caveats explicitly.\n"
            "\n"
            "## Inputs and locked thresholds\n"
            "\n"
            "40-cell × 3-size sweep parquets and per-prompt cache `.npz` files for each motif (induction, successor, S-inhibition), produced by `_run_phase2_*_sweep.py`. Pre-locked thresholds: induction prefix-match > 0.3 (brief §4); successor τ_lift = 0.13496 (§SU-tau); S-inhibition τ_strict = 0.0372 (§S-tau).\n"
            "\n"
            "## Sub-deliverables (§H2-9)\n"
            "\n"
            "1. Joint H1-C sign-test verdict (the registered gate).\n"
            "2. Emergence-step μ table with bootstrap CIs across all 9 (size, motif) cells.\n"
            "3. **Bootstrap reversal-rate per (size, pair)** — empirical reframe of the original \"per-pair descriptive p-values\" sub-deliverable. Replaces the prior-under-exchangeability with the fraction of B=1000 bootstrap replicates in which the predicted ordering does NOT hold.\n"
            "4. Side-by-side emergence-comparison curves (3 panels, one per size; three motif curves per panel).\n"
            "5. Major differences between the three head types — depth, count saturation, cross-category breadth, identity stability.\n"
            "6. Threshold-sensitivity check (μ point estimates with B=1000 bootstrap envelopes at ± 25% threshold variants).\n"
            "7. Verdict, reframed for scale-dependence."
        ),
        md(
            "## Methodological audit trail\n"
            "\n"
            "A reviewer reading just the four Phase-2 deliverables (this notebook + the three `_full_sweep` notebooks) would not see the upstream tooling validation, the copy-suppression pivot, or the threshold-locking notebooks. The full audit trail is:\n"
            "\n"
            "**Tooling validation.** [`tigges_ioi_replication.ipynb`](./tigges_ioi_replication.ipynb) — Tigges 2024 IOI emergence-curve replication on Pythia. Max abs-diff 0.066 < 0.10 vs Tigges 2024 at the 4 directly-shared steps. This is the make-or-break MPS-numerics check that gates every downstream patching result.\n"
            "\n"
            "**Pivot from copy-suppression to S-inhibition.** [`copy_suppression_proof.ipynb`](./copy_suppression_proof.ipynb), [`copy_suppression_pythia_proof.ipynb`](./copy_suppression_pythia_proof.ipynb), [`copy_suppression_emergence_exploration.ipynb`](./copy_suppression_emergence_exploration.ipynb) — pre-pivot evidence that copy-suppression's CSPA proxy fails the GPT-2 gate on Pythia. The pivot to S-inhibition is documented in `PILOT_RESULTS.md` and `HYPOTHESIS.md` §S-0.\n"
            "\n"
            "**S-inhibition detector validation.** [`s_inhibition_proof.ipynb`](./s_inhibition_proof.ipynb) — GPT-2 small replication of Wang 2022 S-inhibition heads. The strict σ-criterion failed by 0.019σ; rank-based override accepted under §S-5b/c (Wang's 4 = ranks #1-#4 of 144). The reasoning is recorded in HYPOTHESIS.md.\n"
            "\n"
            "**Successor detector validation.** [`successor_proof.ipynb`](./successor_proof.ipynb) — GPT-2 small L9H1 reproduction (rank #1 by §SU-1b lift score). The lift-form supersede of the original real-DLA score is documented in HYPOTHESIS.md §SU-1b after a smoke-test failure of the original spec.\n"
            "\n"
            "**Per-motif Phase 2 sweeps.** [`induction_full_sweep.ipynb`](./induction_full_sweep.ipynb), [`successor_full_sweep.ipynb`](./successor_full_sweep.ipynb), [`s_inhibition_full_sweep.ipynb`](./s_inhibition_full_sweep.ipynb) — 40-cell × 3-size emergence curves with bootstrap CIs per motif. The H1-C ordering verdict in this notebook composes those three.\n"
            "\n"
            "**Pre-registration record.** `HYPOTHESIS.md` is the registered specification with appended amendments (§SU, §SU-1b, §SU-tau, §H2, §H2-9-R reframe). Each amendment block has a commit timestamp; the amendment chain is the audit log.\n"
        ),
        md("## Setup"),
        code(
            "import os\n"
            "os.environ.setdefault('PYTORCH_ENABLE_MPS_FALLBACK', '1')\n"
            "\n"
            "import sys\n"
            "from pathlib import Path\n"
            "REPO = Path.cwd().parent if Path.cwd().name == 'notebooks' else Path.cwd()\n"
            "if str(REPO) not in sys.path:\n"
            "    sys.path.insert(0, str(REPO))\n"
            "\n"
            "import numpy as np\n"
            "import pandas as pd\n"
            "import matplotlib.pyplot as plt\n"
            "from notebooks._lib.sweep_io import read_long\n"
            "from src.analysis.phase2_logistic import (\n"
            "    tiered_fit, evaluate_ordering, joint_h1c_test, RIGHT_CENSOR_STEP,\n"
            ")\n"
            "from src.analysis.phase2_bootstrap import (\n"
            "    bootstrap_induction, bootstrap_successor, bootstrap_s_inhibition,\n"
            "    summarize_bootstrap, THRESHOLD_SENSITIVITY_FRACTIONS,\n"
            ")\n"
            "\n"
            "SIZES = ['70m', '160m', '410m']\n"
            "MOTIFS = ['induction', 'successor', 's_inhibition']\n"
            "SIZE_COLOR = {'70m': 'tab:blue', '160m': 'tab:orange', '410m': 'tab:green'}\n"
            "MOTIF_MARKER = {'induction': '^', 'successor': 's', 's_inhibition': 'o'}\n"
            "MOTIF_LINESTYLE = {'induction': '--', 'successor': '-.', 's_inhibition': '-'}\n"
            "\n"
            "INDUCTION_THRESHOLD = 0.3\n"
            "TAU_LIFT = 0.13496\n"
            "TAU_STRICT = 0.0372"
        ),
        md(
            "## Sub-deliverable 2 — Emergence-step μ table with bootstrap CIs\n"
            "\n"
            "For each (size, motif), fit logistic per §H2-3 tiered handling and "
            "compute B=1000 prompt-bootstrap 95% CI on μ per §H2-2."
        ),
        code(
            "df_ind = read_long(REPO / 'data' / 'exploration' / 'phase2_induction_sweep.parquet')\n"
            "df_suc = read_long(REPO / 'data' / 'exploration' / 'phase2_successor_sweep.parquet')\n"
            "df_si = read_long(REPO / 'data' / 'exploration' / 'phase2_s_inhibition_sweep.parquet')\n"
            "\n"
            "def per_size_curve(df, size, threshold, comparator='gt'):\n"
            "    sub = df[df['size'] == size].copy()\n"
            "    if comparator == 'gt':\n"
            "        passes = (sub['score'] > threshold).astype(int)\n"
            "    else:\n"
            "        passes = (sub['score'] >= threshold).astype(int)\n"
            "    sub['passes'] = passes\n"
            "    grouped = sub.groupby('step')['passes'].sum().sort_index()\n"
            "    return grouped.index.values, grouped.values\n"
            "\n"
            "rng = np.random.default_rng(0)\n"
            "rows = []\n"
            "bootstrap_mus = {}  # {(size, motif): mus_array of shape (B,)} for §3 reversal rate\n"
            "for size in SIZES:\n"
            "    for motif, df, threshold, comparator in [\n"
            "        ('induction', df_ind, INDUCTION_THRESHOLD, 'gt'),\n"
            "        ('successor', df_suc, TAU_LIFT, 'gte'),\n"
            "        ('s_inhibition', df_si, TAU_STRICT, 'gte'),\n"
            "    ]:\n"
            "        steps, counts = per_size_curve(df, size, threshold, comparator)\n"
            "        # Bootstrap on cached per-prompt arrays\n"
            "        cache_dir = REPO / 'data' / 'exploration'\n"
            "        if motif == 'induction':\n"
            "            per_seq = {int(s): np.load(cache_dir / 'phase2_induction_per_seq' / f'{size}_step{s}.npz')['per_sequence_scores'] for s in steps}\n"
            "            mus, mu_point = bootstrap_induction(per_seq, threshold, rng, B=1000)\n"
            "        elif motif == 'successor':\n"
            "            per_pp = {}\n"
            "            for s in steps:\n"
            "                npz = np.load(cache_dir / 'phase2_successor_per_prompt' / f'{size}_step{s}.npz')\n"
            "                per_pp[int(s)] = {'real': npz['per_prompt_real'], 'null': npz['per_prompt_null'], 'cats': npz['prompt_categories']}\n"
            "            mus, mu_point = bootstrap_successor(per_pp, threshold, rng, B=1000)\n"
            "        else:\n"
            "            per_pp = {}\n"
            "            nm_layers = {}\n"
            "            for s in steps:\n"
            "                npz = np.load(cache_dir / 'phase2_s_inhibition_per_prompt' / f'{size}_step{s}.npz')\n"
            "                per_pp[int(s)] = npz['per_prompt_delta']\n"
            "                nm_layers[int(s)] = npz['nm_heads'][:, 0].tolist()\n"
            "            a_grp = df_si[(df_si['size'] == size) & (df_si['step'] == steps[0])]\n"
            "            n_layers = int(a_grp['layer'].max() + 1); n_heads = int(a_grp['head'].max() + 1)\n"
            "            sender_layers = np.array([L for L in range(n_layers) for _ in range(n_heads)])\n"
            "            mus, mu_point = bootstrap_s_inhibition(per_pp, threshold, nm_layers, sender_layers, rng, B=1000)\n"
            "        bres = summarize_bootstrap(size, motif, threshold, mus, mu_point)\n"
            "        bootstrap_mus[(size, motif)] = mus  # store for reversal-rate computation\n"
            "        # Per §H2-3, marginal regime uses bootstrap-median μ as point estimate.\n"
            "        fr = tiered_fit(size, motif, steps, counts,\n"
            "                        bootstrap_median_mu=bres.mu_bootstrap_median)\n"
            "        rows.append(dict(\n"
            "            size=size, motif=motif, regime=fr.regime, max_count=fr.max_count,\n"
            "            mu_point=fr.mu, mu_boot_median=bres.mu_bootstrap_median,\n"
            "            ci_low=bres.mu_ci_low, ci_high=bres.mu_ci_high,\n"
            "        ))\n"
            "mu_df = pd.DataFrame(rows)\n"
            "print(mu_df.to_string(index=False, float_format=lambda v: f'{v:.0f}' if v == int(v) else f'{v:.2f}'))"
        ),
        md(
            "## Sub-deliverable 1 — Joint H1-C permutation-test verdict\n"
            "\n"
            "For each size: evaluate μ_ind < μ_suc < μ_S-inhibition strict ordering "
            "with §H2-4 ties-fail policy. Joint verdict per §H2-5: passes if all "
            "3 sizes hold strict ordering."
        ),
        code(
            "orderings = []\n"
            "for size in SIZES:\n"
            "    sub = mu_df[mu_df['size'] == size]\n"
            "    mu_ind = float(sub[sub['motif'] == 'induction']['mu_point'].iloc[0])\n"
            "    mu_suc = float(sub[sub['motif'] == 'successor']['mu_point'].iloc[0])\n"
            "    mu_si = float(sub[sub['motif'] == 's_inhibition']['mu_point'].iloc[0])\n"
            "    orderings.append(evaluate_ordering(size, mu_ind, mu_suc, mu_si))\n"
            "\n"
            "verdict = joint_h1c_test(orderings)\n"
            "print('Per-size ordering check:')\n"
            "for o in orderings:\n"
            "    print(f'  Pythia-{o.size}: μ_ind={o.mu_induction:.0f}, μ_suc={o.mu_successor:.0f}, μ_si={o.mu_s_inhibition:.0f}')\n"
            "    print(f'    pair (ind→suc): {\"HOLDS\" if o.pair_ind_suc_holds else \"FAILS\"}'\n"
            "          + (' [undetermined]' if o.pair_ind_suc_undetermined else ''))\n"
            "    print(f'    pair (suc→si):  {\"HOLDS\" if o.pair_suc_si_holds else \"FAILS\"}'\n"
            "          + (' [undetermined]' if o.pair_suc_si_undetermined else ''))\n"
            "    print(f'    strict ordering: {\"HOLDS\" if o.holds_strict else \"FAILS\"}')\n"
            "print()\n"
            "print(f'Joint H1-C verdict (n_sizes_holding={verdict.n_sizes_holding}/3):')\n"
            "print(f'  joint p (under H_0): {verdict.joint_p_under_h0}')\n"
            "print(f'  PASSES gate (p < 0.005)? {verdict.passes}')"
        ),
        md(
            "## Sub-deliverable 4 — Side-by-side emergence curves\n"
            "\n"
            "Three panels, one per Pythia size. Each panel shows induction, "
            "successor, and S-inhibition count-vs-step curves with their "
            "respective μ point estimates and 95% bootstrap CIs marked."
        ),
        code(
            "fig, axes = plt.subplots(1, 3, figsize=(18, 5), sharey=False)\n"
            "for ax, size in zip(axes, SIZES):\n"
            "    for motif, df, threshold, comparator in [\n"
            "        ('induction', df_ind, INDUCTION_THRESHOLD, 'gt'),\n"
            "        ('successor', df_suc, TAU_LIFT, 'gte'),\n"
            "        ('s_inhibition', df_si, TAU_STRICT, 'gte'),\n"
            "    ]:\n"
            "        steps, counts = per_size_curve(df, size, threshold, comparator)\n"
            "        ax.plot(steps, counts,\n"
            "                marker=MOTIF_MARKER[motif],\n"
            "                linestyle=MOTIF_LINESTYLE[motif],\n"
            "                color=SIZE_COLOR[size],\n"
            "                alpha=0.85, label=motif)\n"
            "        m_row = mu_df[(mu_df['size'] == size) & (mu_df['motif'] == motif)].iloc[0]\n"
            "        if np.isfinite(m_row['mu_point']) and m_row['mu_point'] < RIGHT_CENSOR_STEP - 1:\n"
            "            ax.axvline(m_row['mu_point'], linestyle=':', alpha=0.5,\n"
            "                       color=SIZE_COLOR[size])\n"
            "    ax.set_xscale('symlog', linthresh=1)\n"
            "    ax.set_xlim(0.5, 200000)\n"
            "    ax.set_xlabel('training step (symlog)')\n"
            "    if size == SIZES[0]:\n"
            "        ax.set_ylabel('count of heads passing motif threshold')\n"
            "    ax.set_title(f'Pythia-{size}: H1-C ordering check')\n"
            "    ax.grid(alpha=0.3)\n"
            "    ax.legend(fontsize=9, loc='upper left')\n"
            "fig.suptitle('Side-by-side emergence: induction (▲) → successor (■) → S-inhibition (●)', y=1.02)\n"
            "plt.tight_layout()\n"
            "plt.show()"
        ),
        md(
            "## Sub-deliverable 4b — Layer depth over training: where each motif lives, evolved\n"
            "\n"
            "For each size and motif, plot the **top-head normalized depth** "
            "and **score-weighted centroid normalized depth** across training "
            "steps. This is the time-evolution complement to sub-deliverable "
            "5's final-checkpoint depth snapshot.\n"
            "\n"
            "If the H1-C compositional account is right, the *corrective* "
            "mechanism (S-inhibition) should sit at deeper normalized depth "
            "than the upstream copying mechanisms (induction, successor) "
            "throughout training, not just at the final checkpoint. Tracking "
            "depth over time also surfaces identity-switch events (a top head "
            "at step8k getting replaced by a different layer's head at "
            "step50k) that the static snapshot would miss."
        ),
        code(
            "def depth_trajectory(df, size, score_threshold=None):\n"
            "    \"\"\"Per-cell top-head and score-weighted-centroid normalized depth.\"\"\"\n"
            "    sub = df[df['size'] == size]\n"
            "    rows = []\n"
            "    for step in sorted(sub['step'].unique()):\n"
            "        cell = sub[sub['step'] == step]\n"
            "        if cell.empty:\n"
            "            continue\n"
            "        n_layers = int(cell['layer'].max() + 1)\n"
            "        scores = cell['score'].values.astype(float)\n"
            "        layers = cell['layer'].values.astype(float)\n"
            "        # Top-head normalized depth\n"
            "        top_idx_local = int(np.argmax(scores))\n"
            "        top_norm = float(layers[top_idx_local]) / max(n_layers - 1, 1)\n"
            "        # Score-weighted centroid (clip negatives so anti-motif heads don't pull)\n"
            "        weights = np.clip(scores, 0.0, None)\n"
            "        if weights.sum() > 0:\n"
            "            wl = float((weights * layers).sum() / weights.sum())\n"
            "            wnorm = wl / max(n_layers - 1, 1)\n"
            "        else:\n"
            "            wnorm = float('nan')\n"
            "        rows.append(dict(\n"
            "            step=int(step),\n"
            "            top_norm_depth=top_norm,\n"
            "            weighted_norm_depth=wnorm,\n"
            "            max_score=float(scores.max()),\n"
            "        ))\n"
            "    return pd.DataFrame(rows)\n"
            "\n"
            "depth_traj = {}\n"
            "for size in SIZES:\n"
            "    depth_traj[size] = {\n"
            "        'induction': depth_trajectory(df_ind, size),\n"
            "        'successor': depth_trajectory(df_suc, size),\n"
            "        's_inhibition': depth_trajectory(df_si, size),\n"
            "    }"
        ),
        code(
            "fig, axes = plt.subplots(2, 3, figsize=(18, 9), sharex='col', sharey=False)\n"
            "for col, size in enumerate(SIZES):\n"
            "    # Top row: top-head normalized depth\n"
            "    ax = axes[0, col]\n"
            "    for motif in MOTIFS:\n"
            "        traj = depth_traj[size][motif]\n"
            "        ax.plot(traj['step'], traj['top_norm_depth'],\n"
            "                marker=MOTIF_MARKER[motif], linestyle=MOTIF_LINESTYLE[motif],\n"
            "                color=SIZE_COLOR[size], alpha=0.8, label=motif, markersize=4)\n"
            "    ax.set_xscale('symlog', linthresh=1)\n"
            "    ax.set_xlim(0.5, 200000)\n"
            "    ax.set_ylim(-0.05, 1.05)\n"
            "    ax.set_title(f'Pythia-{size}: top-head depth')\n"
            "    if col == 0:\n"
            "        ax.set_ylabel('top-head normalized depth')\n"
            "    ax.grid(alpha=0.3)\n"
            "    if col == len(SIZES) - 1:\n"
            "        ax.legend(fontsize=9, loc='upper left')\n"
            "    # Add μ point estimates as vertical dashed lines\n"
            "    for motif in MOTIFS:\n"
            "        m_row = mu_df[(mu_df['size'] == size) & (mu_df['motif'] == motif)].iloc[0]\n"
            "        if np.isfinite(m_row['mu_point']) and m_row['mu_point'] < RIGHT_CENSOR_STEP - 1:\n"
            "            ax.axvline(m_row['mu_point'], color=SIZE_COLOR[size],\n"
            "                       linestyle=':', alpha=0.3)\n"
            "\n"
            "    # Bottom row: score-weighted centroid\n"
            "    ax = axes[1, col]\n"
            "    for motif in MOTIFS:\n"
            "        traj = depth_traj[size][motif]\n"
            "        valid = traj.dropna(subset=['weighted_norm_depth'])\n"
            "        ax.plot(valid['step'], valid['weighted_norm_depth'],\n"
            "                marker=MOTIF_MARKER[motif], linestyle=MOTIF_LINESTYLE[motif],\n"
            "                color=SIZE_COLOR[size], alpha=0.8, label=motif, markersize=4)\n"
            "    ax.set_xscale('symlog', linthresh=1)\n"
            "    ax.set_xlim(0.5, 200000)\n"
            "    ax.set_ylim(-0.05, 1.05)\n"
            "    ax.set_xlabel('training step (symlog)')\n"
            "    ax.set_title(f'Pythia-{size}: score-weighted centroid depth')\n"
            "    if col == 0:\n"
            "        ax.set_ylabel('weighted normalized depth')\n"
            "    ax.grid(alpha=0.3)\n"
            "    if col == len(SIZES) - 1:\n"
            "        ax.legend(fontsize=9, loc='upper left')\n"
            "fig.suptitle('Layer depth of each motif across training '\n"
            "             '(induction ▲ dashed / successor ■ dot-dash / S-inhibition ● solid)', y=1.0)\n"
            "plt.tight_layout()\n"
            "plt.show()"
        ),
        md(
            "Reading the plot: each curve traces the layer the *top-scoring* "
            "head of that motif sits at, at each training checkpoint. The "
            "top row shows the strict argmax (sensitive to single-cell noise "
            "but easy to interpret). The bottom row shows the score-weighted "
            "centroid, which is more robust to identity switches — when a "
            "head's score drops and another head takes over, the weighted "
            "centroid moves smoothly while the top-head curve jumps.\n"
            "\n"
            "**Pre-emergence cells (where the motif hasn't fired yet) "
            "produce noisy depth estimates** because the \"top head\" is "
            "essentially the largest noise spike. The faint vertical dashed "
            "lines mark each motif's emergence step μ; reading depth values "
            "to the *right* of those lines is the meaningful interpretation."
        ),
        code(
            "# Final-checkpoint snapshot table for the cross-motif depth comparison\n"
            "rows = []\n"
            "for size in SIZES:\n"
            "    for motif in MOTIFS:\n"
            "        traj = depth_traj[size][motif]\n"
            "        last = traj[traj['step'] == 143000]\n"
            "        if last.empty:\n"
            "            continue\n"
            "        rows.append(dict(\n"
            "            size=size, motif=motif,\n"
            "            top_norm_depth=float(last['top_norm_depth'].iloc[0]),\n"
            "            weighted_norm_depth=float(last['weighted_norm_depth'].iloc[0]),\n"
            "        ))\n"
            "depth_summary = pd.DataFrame(rows)\n"
            "wide = depth_summary.pivot(index='size', columns='motif',\n"
            "                            values=['top_norm_depth', 'weighted_norm_depth'])\n"
            "print('Final-checkpoint normalized depth per (size, motif):')\n"
            "print(wide.to_string(float_format=lambda v: f'{v:.3f}'))"
        ),
        md(
            "## Sub-deliverable 3 — Bootstrap reversal rate per (size, pair)\n"
            "\n"
            "**Reframe of the originally-registered \"per-pair descriptive p-values.\"** The original sub-deliverable computed `0.5 if holds else 1.0` from the point estimates — i.e., the *prior probability* of the observed ordering under exchangeable H_0, dressed as a p-value. That is not a p-value: it is constant by construction within {holds, fails}.\n"
            "\n"
            "Replaced here with the **bootstrap reversal rate**: across the B=1000 per-prompt bootstrap replicates already computed in sub-deliverable 2, what fraction of replicates show the predicted ordering *fail*? This is a real magnitude-aware summary of how robust each per-size pair-ordering is to per-prompt resampling. Censored ties (both μ at the right-censor sentinel) are counted as undetermined per §H2-4 ties-fail and treated as not-holding.\n"
            "\n"
            "Reading the table:\n"
            "- `reversal_rate ≈ 0`: ordering robustly holds across resamples.\n"
            "- `reversal_rate ≈ 0.5`: bootstrap is split — ordering at the point estimate is essentially coincidence given prompt sampling.\n"
            "- `reversal_rate ≈ 1`: ordering robustly fails (or is undetermined under censored ties).\n"
            "\n"
            "Critical for the reframe: the joint sign-test pass in sub-deliverable 1 is a 1-bit-per-size existence claim. The reversal rate is the magnitude-aware companion that surfaces *which* per-size legs of the joint claim are propped up by signal versus by point-estimate happenstance."
        ),
        code(
            "from src.analysis.phase2_bootstrap import bootstrap_pair_reversal_rate\n"
            "\n"
            "PAIRS = [\n"
            "    ('induction', 'successor', 'induction → successor'),\n"
            "    ('successor', 's_inhibition', 'successor → S-inhibition'),\n"
            "    ('induction', 's_inhibition', 'induction → S-inhibition (transitive)'),\n"
            "]\n"
            "\n"
            "rows = []\n"
            "for size in SIZES:\n"
            "    for early_motif, late_motif, label in PAIRS:\n"
            "        result = bootstrap_pair_reversal_rate(\n"
            "            mus_early=bootstrap_mus[(size, early_motif)],\n"
            "            mus_late=bootstrap_mus[(size, late_motif)],\n"
            "            size=size,\n"
            "            motif_early=early_motif,\n"
            "            motif_late=late_motif,\n"
            "        )\n"
            "        rows.append(dict(\n"
            "            size=size,\n"
            "            pair=label,\n"
            "            n_total=result.n_total,\n"
            "            n_holds=result.n_holds,\n"
            "            n_undetermined=result.n_undetermined,\n"
            "            holds_rate=result.holds_rate,\n"
            "            reversal_rate=result.reversal_rate,\n"
            "        ))\n"
            "reversal_df = pd.DataFrame(rows)\n"
            "print('Bootstrap reversal rate per (size, pair) — B=1000 per-prompt resamples:')\n"
            "print(reversal_df.to_string(index=False, float_format=lambda v: f'{v:.3f}'))"
        ),
        md(
            "## What the reversal-rate table says (interpretation guide)\n"
            "\n"
            "Look for three patterns:\n"
            "\n"
            "**Pattern A — robust ordering:** `holds_rate ≈ 1.0`, `reversal_rate ≈ 0.0`. The pair-ordering at this size is propped up by signal that survives per-prompt resampling. This is the strong form of evidence for the registered ordering.\n"
            "\n"
            "**Pattern B — censored vacuous ordering:** `n_undetermined > 0` and `holds_rate < 1`. One or both motifs are right-censored at step143000 in many bootstrap replicates. The point estimate satisfies the inequality only because the later motif failed to emerge — the ordering is mechanically true but not *informative*.\n"
            "\n"
            "**Pattern C — split bootstrap:** `holds_rate ≈ 0.5-0.7`. The sign of the per-prompt bootstrap estimate of (μ_late − μ_early) flips substantially across replicates. The point-estimate pass survived the gate but is fragile.\n"
            "\n"
            "We expect to see Pattern A for 410m's (induction, successor) leg, and Pattern B/C contamination for the 70m S-inhibition leg and 160m S-inhibition leg. This is the central evidence for the §H2-9-R reframe."
        ),
        md(
            "## Sub-deliverable 5 — Major differences between the three head types\n"
            "\n"
            "Cross-motif comparison of structural properties at the final "
            "checkpoint (step143000) per Pythia size. Four properties:\n"
            "\n"
            "- **Depth**: top-head normalized layer (layer / (n_layers - 1)).\n"
            "- **Count saturation**: number of heads passing threshold at step143000.\n"
            "- **Score magnitude**: max score per cell.\n"
            "- **Identity stability**: fraction of step143000 top-3 heads also in top-3 at step25000."
        ),
        code(
            "rows = []\n"
            "for size in SIZES:\n"
            "    for motif, df, threshold, comparator in [\n"
            "        ('induction', df_ind, INDUCTION_THRESHOLD, 'gt'),\n"
            "        ('successor', df_suc, TAU_LIFT, 'gte'),\n"
            "        ('s_inhibition', df_si, TAU_STRICT, 'gte'),\n"
            "    ]:\n"
            "        sub = df[(df['size'] == size) & (df['step'] == 143000)]\n"
            "        n_layers = int(sub['layer'].max() + 1)\n"
            "        if comparator == 'gt':\n"
            "            sat = int((sub['score'] > threshold).sum())\n"
            "        else:\n"
            "            sat = int((sub['score'] >= threshold).sum())\n"
            "        max_idx = int(np.argmax(sub['score'].values))\n"
            "        top_layer = int(sub.iloc[max_idx]['layer'])\n"
            "        max_score = float(sub['score'].max())\n"
            "        # Identity stability: top-3 at 143k vs at 25000 (or nearest).\n"
            "        nearest_25k_step = sorted(df[df['size'] == size]['step'].unique(),\n"
            "                                   key=lambda s: abs(s - 25000))[0]\n"
            "        sub_25k = df[(df['size'] == size) & (df['step'] == nearest_25k_step)]\n"
            "        top3_143k = set(map(tuple, sub.nlargest(3, 'score')[['layer', 'head']].values.tolist()))\n"
            "        top3_25k = set(map(tuple, sub_25k.nlargest(3, 'score')[['layer', 'head']].values.tolist()))\n"
            "        stability = len(top3_143k & top3_25k) / 3.0\n"
            "        rows.append(dict(\n"
            "            size=size, motif=motif,\n"
            "            top_norm_depth=top_layer / max(n_layers - 1, 1),\n"
            "            count_at_saturation=sat,\n"
            "            max_score=max_score,\n"
            "            identity_stability_25k_to_143k=stability,\n"
            "        ))\n"
            "diff_df = pd.DataFrame(rows)\n"
            "print(diff_df.to_string(index=False, float_format=lambda v: f'{v:.3f}'))"
        ),
        md(
            "## Sub-deliverable 6 — Threshold-sensitivity check (B=1000)\n"
            "\n"
            "Vary each motif's locked threshold by ± 25% in 5 increments per §H2-2. At each variant, run the full **B=1000 per-prompt bootstrap** (not B=1 as in earlier drafts) and report both the μ point estimate and the 95% percentile bootstrap CI. The CI envelope is the panel's stochastic-variation reading; the point-estimate curve answers \"does the registered ordering survive plausible threshold mis-specification?\"\n"
            "\n"
            "This panel is *expensive* — 5 thresholds × 3 motifs × 3 sizes × 1000 bootstraps. Cell takes a few minutes."
        ),
        code(
            "rng = np.random.default_rng(2)\n"
            "sens_rows = []\n"
            "for size in SIZES:\n"
            "    for motif, df, threshold, comparator in [\n"
            "        ('induction', df_ind, INDUCTION_THRESHOLD, 'gt'),\n"
            "        ('successor', df_suc, TAU_LIFT, 'gte'),\n"
            "        ('s_inhibition', df_si, TAU_STRICT, 'gte'),\n"
            "    ]:\n"
            "        steps, _ = per_size_curve(df, size, threshold, comparator)\n"
            "        # Pre-load per-prompt arrays once per (size, motif), reuse across thresholds\n"
            "        cache_dir = REPO / 'data' / 'exploration'\n"
            "        if motif == 'induction':\n"
            "            per = {int(s): np.load(cache_dir / 'phase2_induction_per_seq' / f'{size}_step{s}.npz')['per_sequence_scores'] for s in steps}\n"
            "            si_extras = None\n"
            "        elif motif == 'successor':\n"
            "            per = {}\n"
            "            for s in steps:\n"
            "                npz = np.load(cache_dir / 'phase2_successor_per_prompt' / f'{size}_step{s}.npz')\n"
            "                per[int(s)] = {'real': npz['per_prompt_real'], 'null': npz['per_prompt_null'], 'cats': npz['prompt_categories']}\n"
            "            si_extras = None\n"
            "        else:\n"
            "            per = {}; nm_layers = {}\n"
            "            for s in steps:\n"
            "                npz = np.load(cache_dir / 'phase2_s_inhibition_per_prompt' / f'{size}_step{s}.npz')\n"
            "                per[int(s)] = npz['per_prompt_delta']; nm_layers[int(s)] = npz['nm_heads'][:, 0].tolist()\n"
            "            a_grp = df_si[(df_si['size'] == size) & (df_si['step'] == steps[0])]\n"
            "            n_layers = int(a_grp['layer'].max() + 1); n_heads = int(a_grp['head'].max() + 1)\n"
            "            sender_layers = np.array([L for L in range(n_layers) for _ in range(n_heads)])\n"
            "            si_extras = (nm_layers, sender_layers)\n"
            "        for frac in THRESHOLD_SENSITIVITY_FRACTIONS:\n"
            "            thr = threshold * (1.0 + frac)\n"
            "            if motif == 'induction':\n"
            "                mus, mu_point = bootstrap_induction(per, thr, rng, B=1000)\n"
            "            elif motif == 'successor':\n"
            "                mus, mu_point = bootstrap_successor(per, thr, rng, B=1000)\n"
            "            else:\n"
            "                nm_layers_d, sender_layers_arr = si_extras\n"
            "                mus, mu_point = bootstrap_s_inhibition(per, thr, nm_layers_d, sender_layers_arr, rng, B=1000)\n"
            "            bres = summarize_bootstrap(size, motif, thr, mus, mu_point)\n"
            "            sens_rows.append(dict(\n"
            "                size=size, motif=motif, threshold=thr, fraction=frac,\n"
            "                mu_point=mu_point,\n"
            "                ci_low=bres.mu_ci_low, ci_high=bres.mu_ci_high,\n"
            "            ))\n"
            "        print(f'  done: {size}, {motif}')\n"
            "sens_df = pd.DataFrame(sens_rows)\n"
            "\n"
            "fig, axes = plt.subplots(1, 3, figsize=(18, 5), sharey=False)\n"
            "for ax, size in zip(axes, SIZES):\n"
            "    for motif in MOTIFS:\n"
            "        sub = sens_df[(sens_df['size'] == size) & (sens_df['motif'] == motif)].sort_values('threshold')\n"
            "        # Bootstrap envelope (95% CI)\n"
            "        ax.fill_between(sub['fraction'] * 100, sub['ci_low'], sub['ci_high'],\n"
            "                        color=SIZE_COLOR[size], alpha=0.15)\n"
            "        # Point estimate\n"
            "        ax.plot(sub['fraction'] * 100, sub['mu_point'], marker=MOTIF_MARKER[motif],\n"
            "                color=SIZE_COLOR[size], alpha=0.85,\n"
            "                linestyle=MOTIF_LINESTYLE[motif], label=motif)\n"
            "    ax.axvline(0, color='gray', linestyle='--', alpha=0.5)\n"
            "    ax.set_yscale('symlog', linthresh=1)\n"
            "    ax.set_xlabel('threshold variation (%)')\n"
            "    if size == SIZES[0]:\n"
            "        ax.set_ylabel('emergence step μ (point + 95% bootstrap CI envelope)')\n"
            "    ax.set_title(f'Pythia-{size}')\n"
            "    ax.legend(fontsize=8)\n"
            "    ax.grid(alpha=0.3)\n"
            "fig.suptitle('Threshold-sensitivity: μ vs ± 25% threshold variation, with B=1000 bootstrap envelope', y=1.02)\n"
            "plt.tight_layout()\n"
            "plt.show()"
        ),
        md(
            "## Power analysis: μ-uncertainty floor as a function of max_count (post-hoc, §H2-9-R)\n"
            "\n"
            "A reviewer concern about the marginal regime: with `max_count = 3`, the logistic fit is essentially three points above zero, which can be fit by many curves with widely-varying μ. **Why should we trust μ_point to within an order of magnitude when L_true ≈ 3?**\n"
            "\n"
            "We answer this empirically. Simulate logistic emergence with a known true μ, fit it under the observation noise, and report the recovered-μ spread as a function of the saturation level (max_count). Below `max_count = 3`, the recovered μ has an uncertainty floor of roughly an order of magnitude — which is exactly what the bootstrap CIs in sub-deliverable 2 are showing for the marginal cells.\n"
            "\n"
            "This is a sensitivity analysis that quantifies the prior intuition: *small head populations carry weak emergence-step information.* The reframe in sub-deliverable 7 leans on this — a marginal cell is not a confirmation of a clean emergence step; it is a confirmation that a small population starts to satisfy the threshold somewhere in a wide window."
        ),
        code(
            "from src.analysis.phase2_logistic import fit_logistic_to_counts\n"
            "\n"
            "def simulate_recovery(L_true, mu_true=8000.0, k_true=2.0, n_trials=200, rng=None):\n"
            "    \"\"\"Simulate Poisson-noise observation of a logistic curve.\n"
            "\n"
            "    Returns array of recovered μ values under repeated sampling.\n"
            "    \"\"\"\n"
            "    if rng is None:\n"
            "        rng = np.random.default_rng(7)\n"
            "    sim_steps = np.array([int(s) for s in df_ind.step.unique()], dtype=np.int64)\n"
            "    sim_steps = np.sort(sim_steps)\n"
            "    log_steps = np.log(np.maximum(sim_steps.astype(float), 0.5))\n"
            "    true_curve = L_true / (1.0 + np.exp(-k_true * (log_steps - np.log(mu_true))))\n"
            "    recovered = []\n"
            "    for _ in range(n_trials):\n"
            "        observed = rng.poisson(true_curve)\n"
            "        if observed.max() < 2:\n"
            "            continue  # would be censored under §H2-3 rules\n"
            "        try:\n"
            "            _, _, mu_hat = fit_logistic_to_counts(sim_steps, observed)\n"
            "        except Exception:\n"
            "            continue\n"
            "        if np.isfinite(mu_hat):\n"
            "            recovered.append(mu_hat)\n"
            "    return np.array(recovered)\n"
            "\n"
            "L_VALUES = [1, 2, 3, 5, 10, 20]\n"
            "rng = np.random.default_rng(7)\n"
            "power_rows = []\n"
            "for L in L_VALUES:\n"
            "    rec = simulate_recovery(L, rng=rng)\n"
            "    if rec.size == 0:\n"
            "        power_rows.append(dict(L_true=L, n_recovered=0, mu_median=float('nan'),\n"
            "                                mu_p05=float('nan'), mu_p95=float('nan'),\n"
            "                                ratio_p95_over_p05=float('nan')))\n"
            "        continue\n"
            "    p05, p50, p95 = np.percentile(rec, [5, 50, 95])\n"
            "    power_rows.append(dict(\n"
            "        L_true=L, n_recovered=int(rec.size),\n"
            "        mu_median=float(p50), mu_p05=float(p05), mu_p95=float(p95),\n"
            "        ratio_p95_over_p05=float(p95 / max(p05, 1.0)),\n"
            "    ))\n"
            "power_df = pd.DataFrame(power_rows)\n"
            "print('Power analysis: μ-recovery as function of L_true (true peak count).')\n"
            "print('  Underlying μ_true = 8000 steps, k_true = 2.0, Poisson noise on per-step counts.')\n"
            "print('  ratio_p95_over_p05 < 2 = good, > 5 = unusable for ordering.')\n"
            "print(power_df.to_string(index=False, float_format=lambda v: f'{v:.0f}' if v == int(v) else f'{v:.2f}'))"
        ),
        code(
            "fig, ax = plt.subplots(figsize=(8, 5))\n"
            "valid = power_df.dropna(subset=['mu_p05', 'mu_p95', 'mu_median'])\n"
            "ax.fill_between(valid['L_true'], valid['mu_p05'], valid['mu_p95'],\n"
            "                color='tab:gray', alpha=0.3, label='5%-95% recovery range')\n"
            "ax.plot(valid['L_true'], valid['mu_median'], marker='o', color='tab:red',\n"
            "        label='median recovered μ')\n"
            "ax.axhline(8000, color='tab:green', linestyle='--', label='true μ = 8000')\n"
            "ax.set_xlabel('L_true (true peak count of motif heads)')\n"
            "ax.set_ylabel('recovered μ (steps)')\n"
            "ax.set_yscale('symlog', linthresh=10)\n"
            "ax.set_title('μ-recovery uncertainty vs head-count saturation\\n(simulation; Poisson noise on logistic emergence curve)')\n"
            "ax.grid(alpha=0.3)\n"
            "ax.legend()\n"
            "plt.tight_layout()\n"
            "plt.show()"
        ),
        md(
            "**Reading the figure.** The horizontal green line is the true emergence step; the red dot is the median recovered μ; the gray band is the 5%-95% recovery range under repeated noisy observation of the same underlying curve.\n"
            "\n"
            "At `L_true ≥ 5` (the §H2-3 \"emerged\" threshold), the recovery range is narrow — μ is well-determined within ~ ± 30%.\n"
            "\n"
            "At `L_true ∈ {2, 3}` (the §H2-3 \"marginal\" regime), the recovery range spans roughly an order of magnitude. **This is consistent with the bootstrap CI we observe at 70m successor (max_count=2) and 160m S-inhibition (max_count=3).** The marginal cells in sub-deliverable 2 are not anomalously poorly-fit; they are at the prior-information floor for a 3-point logistic fit.\n"
            "\n"
            "At `L_true = 1`, the §H2-3 censored regime applies and the bootstrap-median fallback is used per §H2-3. The simulation here is a sanity check that the §H2-3 tiered handling rule is calibrated correctly.\n"
            "\n"
            "**Implication for the H1-C verdict.** The 70m S-inhibition leg is censored. The 160m S-inhibition leg has L=3, putting its μ-uncertainty at the order-of-magnitude floor identified here. Interpreting these legs as confirmations of a precise μ value would be over-reading the data. The reframe in sub-deliverable 7 explicitly de-emphasizes them in the per-size verdict."
        ),
        md(
            "## Sub-deliverable 7 — Verdict (reframed per §H2-9-R)\n"
            "\n"
            "### What the registered gate says\n"
            "\n"
            "Mechanically: the joint sign test passes with p ≈ 0.00463 < 0.005. Per HYPOTHESIS.md §3 falsification criterion, **the registered H1-C is not falsified.** This statement is correct and we don't soften it.\n"
            "\n"
            "### What the registered gate does NOT say\n"
            "\n"
            "The joint sign test is a 3-bit observation: `(holds_70m, holds_160m, holds_410m)`. Under exchangeable per-size H_0 (each size's three-motif ordering is uniform over 6 permutations), the probability of `(True, True, True)` is (1/6)³ ≈ 0.00463. That is the right p-value for the right null. It is *not* a continuous magnitude-of-evidence statistic and was never intended to be one.\n"
            "\n"
            "Two readings of the gate pass are admissible:\n"
            "\n"
            "1. *(Registered)* The pre-registered ordering hypothesis is supported across three Pythia sizes at the registered alpha. The compositional account that motivated the prediction is consistent with the Phase 2 sweep.\n"
            "2. *(Reframed, §H2-9-R)* The 3-bit pass survives only if you accept censored cells as legitimate \"holds\" against any earlier-emerging motif. With 4/9 cells right-censored or marginal at the upper sentinel, the gate is structurally sensitive to the tiered-fit rule (§H2-3) that elevates `did not emerge during training` to a numerically-larger μ.\n"
            "\n"
            "We register reading (2) as the headline interpretation of Phase 2.\n"
            "\n"
            "### What we actually claim\n"
            "\n"
            "**Robust per-size confirmation:** Pythia-410m only. Both ordering pairs (induction → successor, successor → S-inhibition) emerge with well-fit μ values, low bootstrap reversal rate, and CI separation visible in sub-deliverable 4.\n"
            "\n"
            "**Marginal per-size confirmation:** Pythia-160m. Induction and successor μ are well-fit; S-inhibition's logistic fit hits the upper bound (μ_point = 2,000,000), the bootstrap CI overlaps successor's CI, and the (successor, S-inhibition) pair-ordering is propped up by a marginal regime fit rather than signal.\n"
            "\n"
            "**Censored confirmation:** Pythia-70m. S-inhibition does not emerge during training (max_count = 1 head at step143000); the (successor, S-inhibition) pair satisfies μ_suc < μ_si only because S-inhibition is right-censored at step143000 by §H2-3. This is *vacuous* satisfaction in a strict sense and is the central evidence for scale-dependent emergence of S-inhibition.\n"
            "\n"
            "**Scale-dependence finding (new headline):** S-inhibition's emergence appears scale-dependent in Pythia. It does not emerge at 70m, emerges marginally at 160m, and emerges with a clean fit at 410m. Induction and successor emerge at all three sizes. This is the most reportable Phase 2 finding.\n"
            "\n"
            "**Depth-vs-temporal asymmetry (sub-deliverable 4b):** in 160m and 410m, successor heads sit at *deeper* normalized layer depth than S-inhibition heads. Information flows shallow → deep, so S-inhibition cannot be reading from successor's output if it lives architecturally upstream. The temporal emergence ordering does not, on the current evidence, reflect a compositional architectural ordering. This is reported as a substantive finding distinct from the registered hypothesis.\n"
            "\n"
            "**Identity stability:** Top-3 successor and S-inhibition heads turn over substantially between step25k and step143k (stability 0.0–0.667 across sizes; sub-deliverable 5). The \"emergence step\" abstraction is therefore tracking a count of heads above threshold, not a stable named circuit.\n"
            "\n"
            "### What this paper should be\n"
            "\n"
            "A scale-dependent emergence study with one robust per-size confirmation (410m), interpreted alongside three orthogonal findings (depth ≠ temporal, identity churn, scale dependence of S-inhibition). The registered joint sign test passes; we treat that pass as a necessary-but-not-sufficient milestone, with the Phase 3 / writeup work foregrounding the magnitude-aware findings."
        ),
        code(
            "print('=' * 70)\n"
            "print(' Registered H1-C joint sign test')\n"
            "print('=' * 70)\n"
            "print(f'  n_sizes_holding (sign test): {verdict.n_sizes_holding}/3')\n"
            "print(f'  joint p under exchangeable H_0: {verdict.joint_p_under_h0}')\n"
            "print(f'  registered gate p < 0.005: {\"PASS\" if verdict.passes else \"FAIL\"}')\n"
            "print()\n"
            "print('=' * 70)\n"
            "print(' Reframed per-size verdict (§H2-9-R)')\n"
            "print('=' * 70)\n"
            "for o in orderings:\n"
            "    sub = mu_df[mu_df['size'] == o.size]\n"
            "    regimes = dict(zip(sub['motif'], sub['regime']))\n"
            "    label_parts = []\n"
            "    for m in MOTIFS:\n"
            "        label_parts.append(f'{m}={regimes.get(m, \"?\")}')\n"
            "    regime_str = ', '.join(label_parts)\n"
            "    if all(regimes.get(m) == 'emerged' for m in MOTIFS):\n"
            "        cls = 'ROBUST'\n"
            "    elif any(regimes.get(m) == 'censored' for m in MOTIFS):\n"
            "        cls = 'CENSORED (vacuous against censored motif)'\n"
            "    else:\n"
            "        cls = 'MARGINAL'\n"
            "    print(f'  Pythia-{o.size}: {cls} -- regimes: {regime_str}')\n"
            "print()\n"
            "print('Headline finding: scale-dependent emergence of S-inhibition.')\n"
            "print('Robust ordering confirmation: 410m only.')\n"
            "print('Depth ≠ temporal: S-inhibition lives architecturally upstream of successor in 160m/410m.')\n"
            "print('See sub-deliverables 3, 4b, 5 for the supporting magnitude-aware analyses.')"
        ),
    ]
    return nb


def main() -> None:
    nb = build()
    OUT.parent.mkdir(parents=True, exist_ok=True)
    nbf.write(nb, OUT)
    print(f"Wrote {OUT.relative_to(ROOT)}")


if __name__ == "__main__":
    main()
