"""Build notebooks/h1c_ordering_test.ipynb.

Phase 2 headline deliverable: cross-motif H1-C ordering test (HYPOTHESIS.md
§H2-9 deliverable 4). Loads the three Phase 2 sweep parquets + per-prompt
caches, fits μ_{s,m} with bootstrap CIs, runs the joint H1-C permutation
test, and reports the seven sub-deliverables locked in §H2-9.
"""

from __future__ import annotations

from pathlib import Path

import nbformat as nbf

ROOT = Path(__file__).resolve().parents[1]
OUT = ROOT / "notebooks" / "h1c_ordering_test.ipynb"


def md(text: str) -> nbf.NotebookNode:
    return nbf.v4.new_markdown_cell(text)


def code(src: str) -> nbf.NotebookNode:
    return nbf.v4.new_code_cell(src)


def build() -> nbf.NotebookNode:
    nb = nbf.v4.new_notebook()
    nb["cells"] = [
        md(
            "# H1-C ordering test — joint verdict across 3 motifs × 3 sizes\n"
            "\n"
            "**Phase 2 headline deliverable** (HYPOTHESIS.md §H2-9 deliverable 4).\n"
            "\n"
            "Tests the registered H1-C hypothesis: **μ_induction < μ_successor < μ_S-inhibition** for all three Pythia sizes (70m, 160m, 410m). Joint test under H_0 (exchangeable order in each size) gives p = (1/6)³ ≈ 0.00463; the locked gate is **p < 0.005** (`HYPOTHESIS.md §3 falsification criterion`).\n"
            "\n"
            "Inputs: 40-cell × 3-size sweep parquets and per-prompt cache `.npz` files for each motif (induction, successor, S-inhibition), produced by the three `_run_phase2_*_sweep.py` scripts. Threshold values are pre-locked: induction prefix-match > 0.3 (brief §4); successor τ_lift = 0.13496 (§SU-tau); S-inhibition τ_strict = 0.0372 (§S-tau).\n"
            "\n"
            "**Seven sub-deliverables (§H2-9):**\n"
            "1. Joint H1-C permutation-test verdict (the gate).\n"
            "2. Emergence-step μ table with bootstrap CIs across all 9 (size, motif) cells.\n"
            "3. Per-pair descriptive p-values for the 9 sub-tests (uncorrected, §H2-5).\n"
            "4. Side-by-side emergence-comparison curves (3 panels, one per size; three motif curves per panel).\n"
            "5. Major differences between the three head types — depth, count saturation, cross-category breadth, identity stability.\n"
            "6. Threshold-sensitivity check.\n"
            "7. Verdict."
        ),
        md("## Setup"),
        code(
            "import os\n"
            "os.environ.setdefault('PYTORCH_ENABLE_MPS_FALLBACK', '1')\n"
            "\n"
            "import sys\n"
            "from pathlib import Path\n"
            "REPO = Path.cwd().parent if Path.cwd().name == 'notebooks' else Path.cwd()\n"
            "if str(REPO) not in sys.path:\n"
            "    sys.path.insert(0, str(REPO))\n"
            "\n"
            "import numpy as np\n"
            "import pandas as pd\n"
            "import matplotlib.pyplot as plt\n"
            "from notebooks._lib.sweep_io import read_long\n"
            "from src.analysis.phase2_logistic import (\n"
            "    tiered_fit, evaluate_ordering, joint_h1c_test, RIGHT_CENSOR_STEP,\n"
            ")\n"
            "from src.analysis.phase2_bootstrap import (\n"
            "    bootstrap_induction, bootstrap_successor, bootstrap_s_inhibition,\n"
            "    summarize_bootstrap, THRESHOLD_SENSITIVITY_FRACTIONS,\n"
            ")\n"
            "\n"
            "SIZES = ['70m', '160m', '410m']\n"
            "MOTIFS = ['induction', 'successor', 's_inhibition']\n"
            "SIZE_COLOR = {'70m': 'tab:blue', '160m': 'tab:orange', '410m': 'tab:green'}\n"
            "MOTIF_MARKER = {'induction': '^', 'successor': 's', 's_inhibition': 'o'}\n"
            "MOTIF_LINESTYLE = {'induction': '--', 'successor': '-.', 's_inhibition': '-'}\n"
            "\n"
            "INDUCTION_THRESHOLD = 0.3\n"
            "TAU_LIFT = 0.13496\n"
            "TAU_STRICT = 0.0372"
        ),
        md(
            "## Sub-deliverable 2 — Emergence-step μ table with bootstrap CIs\n"
            "\n"
            "For each (size, motif), fit logistic per §H2-3 tiered handling and "
            "compute B=1000 prompt-bootstrap 95% CI on μ per §H2-2."
        ),
        code(
            "df_ind = read_long(REPO / 'data' / 'exploration' / 'phase2_induction_sweep.parquet')\n"
            "df_suc = read_long(REPO / 'data' / 'exploration' / 'phase2_successor_sweep.parquet')\n"
            "df_si = read_long(REPO / 'data' / 'exploration' / 'phase2_s_inhibition_sweep.parquet')\n"
            "\n"
            "def per_size_curve(df, size, threshold, comparator='gt'):\n"
            "    sub = df[df['size'] == size].copy()\n"
            "    if comparator == 'gt':\n"
            "        passes = (sub['score'] > threshold).astype(int)\n"
            "    else:\n"
            "        passes = (sub['score'] >= threshold).astype(int)\n"
            "    sub['passes'] = passes\n"
            "    grouped = sub.groupby('step')['passes'].sum().sort_index()\n"
            "    return grouped.index.values, grouped.values\n"
            "\n"
            "rng = np.random.default_rng(0)\n"
            "rows = []\n"
            "for size in SIZES:\n"
            "    for motif, df, threshold, comparator in [\n"
            "        ('induction', df_ind, INDUCTION_THRESHOLD, 'gt'),\n"
            "        ('successor', df_suc, TAU_LIFT, 'gte'),\n"
            "        ('s_inhibition', df_si, TAU_STRICT, 'gte'),\n"
            "    ]:\n"
            "        steps, counts = per_size_curve(df, size, threshold, comparator)\n"
            "        # Bootstrap on cached per-prompt arrays\n"
            "        cache_dir = REPO / 'data' / 'exploration'\n"
            "        if motif == 'induction':\n"
            "            per_seq = {int(s): np.load(cache_dir / 'phase2_induction_per_seq' / f'{size}_step{s}.npz')['per_sequence_scores'] for s in steps}\n"
            "            mus, mu_point = bootstrap_induction(per_seq, threshold, rng, B=1000)\n"
            "        elif motif == 'successor':\n"
            "            per_pp = {}\n"
            "            for s in steps:\n"
            "                npz = np.load(cache_dir / 'phase2_successor_per_prompt' / f'{size}_step{s}.npz')\n"
            "                per_pp[int(s)] = {'real': npz['per_prompt_real'], 'null': npz['per_prompt_null'], 'cats': npz['prompt_categories']}\n"
            "            mus, mu_point = bootstrap_successor(per_pp, threshold, rng, B=1000)\n"
            "        else:\n"
            "            per_pp = {}\n"
            "            nm_layers = {}\n"
            "            for s in steps:\n"
            "                npz = np.load(cache_dir / 'phase2_s_inhibition_per_prompt' / f'{size}_step{s}.npz')\n"
            "                per_pp[int(s)] = npz['per_prompt_delta']\n"
            "                nm_layers[int(s)] = npz['nm_heads'][:, 0].tolist()\n"
            "            a_grp = df_si[(df_si['size'] == size) & (df_si['step'] == steps[0])]\n"
            "            n_layers = int(a_grp['layer'].max() + 1); n_heads = int(a_grp['head'].max() + 1)\n"
            "            sender_layers = np.array([L for L in range(n_layers) for _ in range(n_heads)])\n"
            "            mus, mu_point = bootstrap_s_inhibition(per_pp, threshold, nm_layers, sender_layers, rng, B=1000)\n"
            "        bres = summarize_bootstrap(size, motif, threshold, mus, mu_point)\n"
            "        fr = tiered_fit(size, motif, steps, counts)\n"
            "        rows.append(dict(\n"
            "            size=size, motif=motif, regime=fr.regime, max_count=fr.max_count,\n"
            "            mu_point=fr.mu, mu_boot_median=bres.mu_bootstrap_median,\n"
            "            ci_low=bres.mu_ci_low, ci_high=bres.mu_ci_high,\n"
            "        ))\n"
            "mu_df = pd.DataFrame(rows)\n"
            "print(mu_df.to_string(index=False, float_format=lambda v: f'{v:.0f}' if v == int(v) else f'{v:.2f}'))"
        ),
        md(
            "## Sub-deliverable 1 — Joint H1-C permutation-test verdict\n"
            "\n"
            "For each size: evaluate μ_ind < μ_suc < μ_S-inhibition strict ordering "
            "with §H2-4 ties-fail policy. Joint verdict per §H2-5: passes if all "
            "3 sizes hold strict ordering."
        ),
        code(
            "orderings = []\n"
            "for size in SIZES:\n"
            "    sub = mu_df[mu_df['size'] == size]\n"
            "    mu_ind = float(sub[sub['motif'] == 'induction']['mu_point'].iloc[0])\n"
            "    mu_suc = float(sub[sub['motif'] == 'successor']['mu_point'].iloc[0])\n"
            "    mu_si = float(sub[sub['motif'] == 's_inhibition']['mu_point'].iloc[0])\n"
            "    orderings.append(evaluate_ordering(size, mu_ind, mu_suc, mu_si))\n"
            "\n"
            "verdict = joint_h1c_test(orderings)\n"
            "print('Per-size ordering check:')\n"
            "for o in orderings:\n"
            "    print(f'  Pythia-{o.size}: μ_ind={o.mu_induction:.0f}, μ_suc={o.mu_successor:.0f}, μ_si={o.mu_s_inhibition:.0f}')\n"
            "    print(f'    pair (ind→suc): {\"HOLDS\" if o.pair_ind_suc_holds else \"FAILS\"}'\n"
            "          + (' [undetermined]' if o.pair_ind_suc_undetermined else ''))\n"
            "    print(f'    pair (suc→si):  {\"HOLDS\" if o.pair_suc_si_holds else \"FAILS\"}'\n"
            "          + (' [undetermined]' if o.pair_suc_si_undetermined else ''))\n"
            "    print(f'    strict ordering: {\"HOLDS\" if o.holds_strict else \"FAILS\"}')\n"
            "print()\n"
            "print(f'Joint H1-C verdict (n_sizes_holding={verdict.n_sizes_holding}/3):')\n"
            "print(f'  joint p (under H_0): {verdict.joint_p_under_h0}')\n"
            "print(f'  PASSES gate (p < 0.005)? {verdict.passes}')"
        ),
        md(
            "## Sub-deliverable 4 — Side-by-side emergence curves\n"
            "\n"
            "Three panels, one per Pythia size. Each panel shows induction, "
            "successor, and S-inhibition count-vs-step curves with their "
            "respective μ point estimates and 95% bootstrap CIs marked."
        ),
        code(
            "fig, axes = plt.subplots(1, 3, figsize=(18, 5), sharey=False)\n"
            "for ax, size in zip(axes, SIZES):\n"
            "    for motif, df, threshold, comparator in [\n"
            "        ('induction', df_ind, INDUCTION_THRESHOLD, 'gt'),\n"
            "        ('successor', df_suc, TAU_LIFT, 'gte'),\n"
            "        ('s_inhibition', df_si, TAU_STRICT, 'gte'),\n"
            "    ]:\n"
            "        steps, counts = per_size_curve(df, size, threshold, comparator)\n"
            "        ax.plot(steps, counts,\n"
            "                marker=MOTIF_MARKER[motif],\n"
            "                linestyle=MOTIF_LINESTYLE[motif],\n"
            "                color=SIZE_COLOR[size],\n"
            "                alpha=0.85, label=motif)\n"
            "        m_row = mu_df[(mu_df['size'] == size) & (mu_df['motif'] == motif)].iloc[0]\n"
            "        if np.isfinite(m_row['mu_point']) and m_row['mu_point'] < RIGHT_CENSOR_STEP - 1:\n"
            "            ax.axvline(m_row['mu_point'], linestyle=':', alpha=0.5,\n"
            "                       color=SIZE_COLOR[size])\n"
            "    ax.set_xscale('symlog', linthresh=1)\n"
            "    ax.set_xlim(0.5, 200000)\n"
            "    ax.set_xlabel('training step (symlog)')\n"
            "    if size == SIZES[0]:\n"
            "        ax.set_ylabel('count of heads passing motif threshold')\n"
            "    ax.set_title(f'Pythia-{size}: H1-C ordering check')\n"
            "    ax.grid(alpha=0.3)\n"
            "    ax.legend(fontsize=9, loc='upper left')\n"
            "fig.suptitle('Side-by-side emergence: induction (▲) → successor (■) → S-inhibition (●)', y=1.02)\n"
            "plt.tight_layout()\n"
            "plt.show()"
        ),
        md(
            "## Sub-deliverable 3 — Per-pair descriptive p-values\n"
            "\n"
            "Per (size, ordering-pair): compute a descriptive p-value for "
            "*how unlikely* the observed ordering is under H_0 of exchangeable "
            "order. With μ point estimates only, each pairwise ordering has "
            "p = 0.5 under H_0 (μ_a < μ_b is one of two equally-likely orderings). "
            "Per-pair p reported uncorrected per §H2-5."
        ),
        code(
            "rows = []\n"
            "for o in orderings:\n"
            "    rows.append(dict(\n"
            "        size=o.size,\n"
            "        pair='induction → successor',\n"
            "        holds=o.pair_ind_suc_holds,\n"
            "        undetermined=o.pair_ind_suc_undetermined,\n"
            "        descriptive_p=0.5 if o.pair_ind_suc_holds else 1.0,\n"
            "    ))\n"
            "    rows.append(dict(\n"
            "        size=o.size,\n"
            "        pair='successor → S-inhibition',\n"
            "        holds=o.pair_suc_si_holds,\n"
            "        undetermined=o.pair_suc_si_undetermined,\n"
            "        descriptive_p=0.5 if o.pair_suc_si_holds else 1.0,\n"
            "    ))\n"
            "    # Implied transitive: induction → S-inhibition\n"
            "    o_implied_holds = o.pair_ind_suc_holds and o.pair_suc_si_holds\n"
            "    rows.append(dict(\n"
            "        size=o.size,\n"
            "        pair='induction → S-inhibition',\n"
            "        holds=o_implied_holds,\n"
            "        undetermined=False,\n"
            "        descriptive_p=0.5 if o_implied_holds else 1.0,\n"
            "    ))\n"
            "pair_df = pd.DataFrame(rows)\n"
            "print(pair_df.to_string(index=False))"
        ),
        md(
            "## Sub-deliverable 5 — Major differences between the three head types\n"
            "\n"
            "Cross-motif comparison of structural properties at the final "
            "checkpoint (step143000) per Pythia size. Four properties:\n"
            "\n"
            "- **Depth**: top-head normalized layer (layer / (n_layers - 1)).\n"
            "- **Count saturation**: number of heads passing threshold at step143000.\n"
            "- **Score magnitude**: max score per cell.\n"
            "- **Identity stability**: fraction of step143000 top-3 heads also in top-3 at step25000."
        ),
        code(
            "rows = []\n"
            "for size in SIZES:\n"
            "    for motif, df, threshold, comparator in [\n"
            "        ('induction', df_ind, INDUCTION_THRESHOLD, 'gt'),\n"
            "        ('successor', df_suc, TAU_LIFT, 'gte'),\n"
            "        ('s_inhibition', df_si, TAU_STRICT, 'gte'),\n"
            "    ]:\n"
            "        sub = df[(df['size'] == size) & (df['step'] == 143000)]\n"
            "        n_layers = int(sub['layer'].max() + 1)\n"
            "        if comparator == 'gt':\n"
            "            sat = int((sub['score'] > threshold).sum())\n"
            "        else:\n"
            "            sat = int((sub['score'] >= threshold).sum())\n"
            "        max_idx = int(np.argmax(sub['score'].values))\n"
            "        top_layer = int(sub.iloc[max_idx]['layer'])\n"
            "        max_score = float(sub['score'].max())\n"
            "        # Identity stability: top-3 at 143k vs at 25000 (or nearest).\n"
            "        nearest_25k_step = sorted(df[df['size'] == size]['step'].unique(),\n"
            "                                   key=lambda s: abs(s - 25000))[0]\n"
            "        sub_25k = df[(df['size'] == size) & (df['step'] == nearest_25k_step)]\n"
            "        top3_143k = set(map(tuple, sub.nlargest(3, 'score')[['layer', 'head']].values.tolist()))\n"
            "        top3_25k = set(map(tuple, sub_25k.nlargest(3, 'score')[['layer', 'head']].values.tolist()))\n"
            "        stability = len(top3_143k & top3_25k) / 3.0\n"
            "        rows.append(dict(\n"
            "            size=size, motif=motif,\n"
            "            top_norm_depth=top_layer / max(n_layers - 1, 1),\n"
            "            count_at_saturation=sat,\n"
            "            max_score=max_score,\n"
            "            identity_stability_25k_to_143k=stability,\n"
            "        ))\n"
            "diff_df = pd.DataFrame(rows)\n"
            "print(diff_df.to_string(index=False, float_format=lambda v: f'{v:.3f}'))"
        ),
        md(
            "## Sub-deliverable 6 — Threshold-sensitivity check\n"
            "\n"
            "Vary each motif's locked threshold by ± 25% in 5 increments. Does "
            "the H1-C ordering still hold under reasonable threshold mis-"
            "specification? Per §H2-2, we report μ point estimate at each "
            "threshold variant per (size, motif)."
        ),
        code(
            "rng = np.random.default_rng(2)\n"
            "sens_rows = []\n"
            "for size in SIZES:\n"
            "    for motif, df, threshold, comparator in [\n"
            "        ('induction', df_ind, INDUCTION_THRESHOLD, 'gt'),\n"
            "        ('successor', df_suc, TAU_LIFT, 'gte'),\n"
            "        ('s_inhibition', df_si, TAU_STRICT, 'gte'),\n"
            "    ]:\n"
            "        steps, _ = per_size_curve(df, size, threshold, comparator)\n"
            "        for frac in THRESHOLD_SENSITIVITY_FRACTIONS:\n"
            "            thr = threshold * (1.0 + frac)\n"
            "            cache_dir = REPO / 'data' / 'exploration'\n"
            "            if motif == 'induction':\n"
            "                per = {int(s): np.load(cache_dir / 'phase2_induction_per_seq' / f'{size}_step{s}.npz')['per_sequence_scores'] for s in steps}\n"
            "                _, mu = bootstrap_induction(per, thr, rng, B=1)\n"
            "            elif motif == 'successor':\n"
            "                per = {}\n"
            "                for s in steps:\n"
            "                    npz = np.load(cache_dir / 'phase2_successor_per_prompt' / f'{size}_step{s}.npz')\n"
            "                    per[int(s)] = {'real': npz['per_prompt_real'], 'null': npz['per_prompt_null'], 'cats': npz['prompt_categories']}\n"
            "                _, mu = bootstrap_successor(per, thr, rng, B=1)\n"
            "            else:\n"
            "                per = {}; nm_layers = {}\n"
            "                for s in steps:\n"
            "                    npz = np.load(cache_dir / 'phase2_s_inhibition_per_prompt' / f'{size}_step{s}.npz')\n"
            "                    per[int(s)] = npz['per_prompt_delta']; nm_layers[int(s)] = npz['nm_heads'][:, 0].tolist()\n"
            "                a_grp = df_si[(df_si['size'] == size) & (df_si['step'] == steps[0])]\n"
            "                n_layers = int(a_grp['layer'].max() + 1); n_heads = int(a_grp['head'].max() + 1)\n"
            "                sender_layers = np.array([L for L in range(n_layers) for _ in range(n_heads)])\n"
            "                _, mu = bootstrap_s_inhibition(per, thr, nm_layers, sender_layers, rng, B=1)\n"
            "            sens_rows.append(dict(size=size, motif=motif, threshold=thr, fraction=frac, mu_point=mu))\n"
            "sens_df = pd.DataFrame(sens_rows)\n"
            "\n"
            "fig, axes = plt.subplots(1, 3, figsize=(18, 5), sharey=False)\n"
            "for ax, size in zip(axes, SIZES):\n"
            "    for motif in MOTIFS:\n"
            "        sub = sens_df[(sens_df['size'] == size) & (sens_df['motif'] == motif)].sort_values('threshold')\n"
            "        ax.plot(sub['fraction'] * 100, sub['mu_point'], marker=MOTIF_MARKER[motif],\n"
            "                color=SIZE_COLOR[size], alpha=0.85,\n"
            "                linestyle=MOTIF_LINESTYLE[motif], label=motif)\n"
            "    ax.axvline(0, color='gray', linestyle='--', alpha=0.5)\n"
            "    ax.set_yscale('symlog', linthresh=1)\n"
            "    ax.set_xlabel('threshold variation (%)')\n"
            "    if size == SIZES[0]:\n"
            "        ax.set_ylabel('emergence step μ')\n"
            "    ax.set_title(f'Pythia-{size}')\n"
            "    ax.legend(fontsize=8)\n"
            "    ax.grid(alpha=0.3)\n"
            "fig.suptitle('Threshold-sensitivity bracket: μ vs ± 25% threshold variation', y=1.02)\n"
            "plt.tight_layout()\n"
            "plt.show()"
        ),
        md(
            "## Sub-deliverable 7 — Verdict\n"
            "\n"
            "Phase 2 H1-C joint verdict and interpretation. Specific findings depend on the data; populate after re-execution."
        ),
        code(
            "if verdict.passes:\n"
            "    print('=' * 60)\n"
            "    print(f'H1-C HOLDS — joint test PASSES (p < 0.005 gate)')\n"
            "    print('=' * 60)\n"
            "    print(f'  joint p (under H_0): {verdict.joint_p_under_h0:.5f}')\n"
            "    print(f'  All {verdict.n_sizes_holding}/3 sizes show strict μ_ind < μ_suc < μ_S-inhibition.')\n"
            "    print()\n"
            "    print('The registered H1-C compositional account is supported at the Phase 2 resolution.')\n"
            "else:\n"
            "    print('=' * 60)\n"
            "    print(f'H1-C DOES NOT HOLD JOINTLY — joint test FAILS')\n"
            "    print('=' * 60)\n"
            "    print(f'  n_sizes_holding: {verdict.n_sizes_holding}/3')\n"
            "    print(f'  joint p (under H_0): {verdict.joint_p_under_h0}')\n"
            "    print()\n"
            "    print('The registered H1-C compositional account is NOT supported jointly at p < 0.005.')\n"
            "    print('Per HYPOTHESIS.md §3 falsification criterion, the hypothesis is falsified for the joint claim.')\n"
            "    print('Per-size and per-pair descriptive results above remain interpretable as findings.')"
        ),
    ]
    return nb


def main() -> None:
    nb = build()
    OUT.parent.mkdir(parents=True, exist_ok=True)
    nbf.write(nb, OUT)
    print(f"Wrote {OUT.relative_to(ROOT)}")


if __name__ == "__main__":
    main()
